import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const ORIGIN = "https://williansss06-cpu.github.io";
const headers = {
  "Access-Control-Allow-Origin": ORIGIN,
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Content-Type": "application/json; charset=utf-8",
};
const MONTHS = ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"];
type Row = Record<string, unknown>;
type Turn = { role: "user" | "assistant"; content: string; intent?: string };
type Context = { permitido?: boolean; operacoes?: Row[]; ano?: number; mes?: number; modulo?: string; atualizado_em?: string; indicadores?: Row[]; resultados?: Row[]; resultados_historico?: Row[]; sla?: Row[]; acoes?: Row[]; acessos?: Record<string, boolean>; absenteismo?: { mensal?: Row[]; motivos?: Row[]; areas?: Row[]; pessoas?: Row[]; recorrentes?: Row[]; recorrentes_mes?: Row[] } };
type Intent = "executive_summary" | "absenteismo" | "absenteismo_contribuidores" | "absenteismo_recorrencia" | "absenteismo_tendencia" | "indicadores_abaixo_meta" | "indicador_queda" | "ofensores" | "acoes_atrasadas" | "sla_neolog" | "operacao" | "screen" | "unknown";

const response = (data: unknown, status = 200) => new Response(JSON.stringify(data), { status, headers });
const num = (value: unknown) => { const n = Number(value); return Number.isFinite(n) ? n : 0; };
const br = (value: unknown, digits = 2) => num(value).toLocaleString("pt-BR", { minimumFractionDigits: digits, maximumFractionDigits: digits });
const norm = (value: unknown) => String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
const period = (c: Context) => `${MONTHS[Math.max(0, num(c.mes) - 1)] ?? "mês"}/${c.ano ?? "ano"}`;
const operation = (c: Context) => (c.operacoes ?? []).map((x) => String(x.nome ?? x.codigo ?? "operação")).join(" + ") || "operação autorizada";
const source = (c: Context) => `Fonte: ${operation(c)} | Período analisado: ${period(c)} | Dados atualizados: ${c.atualizado_em ? new Date(c.atualizado_em).toLocaleString("pt-BR") : "agora"}`;
const absRows = (c: Context) => c.absenteismo ?? {};
const recurring = (c: Context) => { const a = absRows(c); return Array.isArray(a.recorrentes_mes) ? a.recorrentes_mes : (a.recorrentes ?? []); };
const indicators = (c: Context) => (c.indicadores ?? []).map((i) => { const r = (c.resultados ?? []).find((x) => Number(x.indicador_id) === Number(i.id)); const actual = r?.resultado == null ? null : num(r.resultado); const target = num(i.meta); const lower = String(i.polaridade ?? "MAIOR").toUpperCase() === "MENOR"; return { name: String(i.nome ?? "Indicador"), result: actual, target, status: actual == null ? "sem resultado" : (lower ? actual <= target : actual >= target) ? "dentro da meta" : "abaixo da meta", format: String(i.formato ?? "PERCENT"), polarity: String(i.polaridade ?? "MAIOR") }; });

function previousIntent(conversation: Turn[]) { return [...conversation].reverse().find((x) => x.role === "assistant" && x.intent)?.intent as Intent | undefined; }
function inferIntent(question: string, mode: string, conversation: Turn[]): { intent: Intent; label: string; reason: string } {
  const q = norm(question), prev = previousIntent(conversation), abs = /absenteismo|afastamento|faltas?|atestado|improdutiv|dias de afastamento/.test(q);
  if (mode === "monthly") return { intent: "executive_summary", label: "Análise Executiva do Mês", reason: "modo mensal" };
  if (mode === "screen") return { intent: "screen", label: "Análise da tela atual", reason: "análise contextual" };
  if (/sla|neolog|pontuacao/.test(q)) return { intent: "sla_neolog", label: "SLA NEOLOG", reason: "termos de SLA" };
  if (/como esta a operacao|situacao da operacao|operacao ache|operacao glp|operacao matriz/.test(q)) return { intent: "operacao", label: "Operação", reason: "pergunta sobre operação" };
  if (/\bacao\b|\bacoes\b|plano de acao|vencid|atrasad|prazo/.test(q)) return { intent: "acoes_atrasadas", label: "Planos de Ação", reason: "termos de ação ou prazo" };
  if (/abaixo da meta|fora da meta|indicadores? .*meta|metas? .*indicador/.test(q)) return { intent: "indicadores_abaixo_meta", label: "Indicadores abaixo da meta", reason: "pergunta sobre meta" };
  if (/piorou|piora|caiu|queda|deterior|compar|mes anterior|ultimos? (2|3|4|5|6|meses)|tendencia|evolucao/.test(q)) return abs || prev?.startsWith("absenteismo") ? { intent: "absenteismo_tendencia", label: "Tendência de Absenteísmo", reason: "comparação de absenteísmo" } : { intent: "indicador_queda", label: "Quedas e pioras", reason: "comparação histórica" };
  if (/quem mais|quem contribuiu|contribuiram|ofensor|principais ofensores|maior impacto|concentr/.test(q)) return abs || prev?.startsWith("absenteismo") ? { intent: "absenteismo_contribuidores", label: "Contribuidores do Absenteísmo", reason: "concentração de horas" } : { intent: "ofensores", label: "Principais ofensores", reason: "concentração de impacto" };
  if (/recorrent|representam do total|percentual do total|motivos? .*grupo|area .*concentr/.test(q) && (abs || prev?.startsWith("absenteismo"))) return { intent: "absenteismo_recorrencia", label: "Recorrência do Absenteísmo", reason: "recorrência" };
  if (abs) return { intent: "absenteismo", label: "Absenteísmo", reason: "termos de absenteísmo" };
  if (/operacao|ache|glp|matriz/.test(q)) return { intent: "operacao", label: "Operação", reason: "termos de operação" };
  if (/atencao|prioriz|resumo|visao executiva|situacao geral/.test(q)) return { intent: "executive_summary", label: "Resumo Executivo", reason: "visão geral" };
  if (/esse|esta|isso|eles|essas pessoas|esse grupo|quanto eles|e quanto|por que isso|qual deles/.test(q) && prev) return { intent: prev, label: prev, reason: "continuidade" };
  return { intent: "unknown", label: "Consulta operacional", reason: "intenção não identificada" };
}

function indicatorDeclines(c: Context) {
  const groups = new Map<number, Row[]>();
  for (const row of c.resultados_historico ?? []) { const id = Number(row.indicador_id); if (!Number.isFinite(id)) continue; groups.set(id, [...(groups.get(id) ?? []), row]); }
  const output: Row[] = [];
  for (const rows of groups.values()) { rows.sort((a, b) => num(a.mes) - num(b.mes)); if (rows.length < 2) continue; const p = rows.at(-2), cur = rows.at(-1); if (p?.resultado == null || cur?.resultado == null) continue; const before = num(p.resultado), now = num(cur.resultado), lower = String(cur.polaridade ?? "MAIOR").toUpperCase() === "MENOR"; if (lower ? now > before : now < before) output.push({ indicador: cur.indicador, anterior: before, atual: now, variacao: now - before }); }
  return output.sort((a, b) => Math.abs(num(b.variacao)) - Math.abs(num(a.variacao)));
}
function records(c: Context, intent: Intent) {
  const a = absRows(c), out: Record<string, number> = {}, add = (name: string, value: unknown) => { out[name] = Array.isArray(value) ? value.length : 0; };
  if (["absenteismo", "absenteismo_contribuidores", "absenteismo_recorrencia", "absenteismo_tendencia", "ofensores"].includes(intent)) { add("absenteismo_registros.mensal", a.mensal); add("absenteismo_registros.motivos", a.motivos); add("absenteismo_registros.areas", a.areas); add("absenteismo_registros.pessoas", a.pessoas); add("absenteismo_registros.recorrentes", recurring(c)); }
  if (["indicadores_abaixo_meta", "indicador_queda", "ofensores", "executive_summary", "screen", "unknown"].includes(intent)) { add("sustentacao_indicadores", c.indicadores); add("sustentacao_resultados", c.resultados); if (intent === "indicador_queda") add("sustentacao_resultados_historicos", c.resultados_historico); }
  if (["acoes_atrasadas", "executive_summary", "screen", "unknown"].includes(intent)) add("sustentacao_plano_acao", c.acoes);
  if (["sla_neolog", "executive_summary", "screen", "unknown"].includes(intent)) add("sustentacao_sla_neolog_pontuacoes", c.sla);
  if (intent === "operacao") add("sustentacao_operacoes", c.operacoes);
  return out;
}
function compact(c: Context, intent: Intent) { const a = absRows(c), base = { header: source(c), period: period(c), access: c.acessos ?? {}, operation: c.operacoes ?? [] }; if (intent === "absenteismo" || intent.startsWith("absenteismo_")) return { ...base, absenteismo: { mensal: a.mensal ?? [], motivos: (a.motivos ?? []).slice(0, 10), areas: (a.areas ?? []).slice(0, 10), pessoas: (a.pessoas ?? []).slice(0, 10), recorrentes: recurring(c).slice(0, 20) } }; if (intent === "indicadores_abaixo_meta" || intent === "indicador_queda") return { ...base, indicadores: indicators(c), resultados: c.resultados ?? [], resultados_historico: (c.resultados_historico ?? []).slice(0, 100), acoes: c.acoes ?? [] }; if (intent === "acoes_atrasadas") return { ...base, acoes: c.acoes ?? [], indicadores: indicators(c) }; if (intent === "sla_neolog") return { ...base, sla: (c.sla ?? []).slice(0, 100), indicadores: indicators(c) }; return { ...base, indicadores: indicators(c), absenteismo: { mensal: a.mensal ?? [], motivos: (a.motivos ?? []).slice(0, 10), areas: (a.areas ?? []).slice(0, 10), pessoas: (a.pessoas ?? []).slice(0, 10), recorrentes: recurring(c).slice(0, 10) }, sla: (c.sla ?? []).slice(0, 100), acoes: (c.acoes ?? []).slice(0, 100) }; }
function suggestions(intent: Intent, c: Context) { const a = absRows(c), access = c.acessos ?? {}, out: string[] = [], push = (x: string, ok = true) => { if (ok && !out.includes(x)) out.push(x); }; if (intent.startsWith("absenteismo")) { push("Quem mais contribuiu para esse resultado?", (a.pessoas ?? []).length > 0); push("Quanto os recorrentes representam do total?", recurring(c).length > 0); push("Qual área teve a maior concentração?", (a.areas ?? []).length > 0); push("Compare com os últimos 3 meses", (a.mensal ?? []).length >= 3); push("Quais ações devemos acompanhar?", access.plano_acao === true && (c.acoes ?? []).length > 0); } if (intent === "indicadores_abaixo_meta" || intent === "indicador_queda") { const below = indicators(c).filter(x => x.status === "abaixo da meta"); push("Por que este indicador caiu?", below.length > 0); push("Há plano de ação relacionado?", below.length > 0 && access.plano_acao === true); push("Esse problema é recorrente?", below.length > 0); } if (intent === "acoes_atrasadas") { const late = (c.acoes ?? []).filter(x => x.data_fim && new Date(String(x.data_fim)).getTime() < Date.now()); push("Quais responsáveis concentram mais ações atrasadas?", late.length > 0); push("Quais ações têm indicador relacionado?", late.some(x => x.indicador_id != null)); } if (intent === "sla_neolog") { push("Como a pontuação evoluiu nos meses disponíveis?", (c.sla ?? []).length > 1); push("Qual indicador mais contribuiu para a pontuação?", (c.sla ?? []).length > 0); } if (["executive_summary", "screen", "unknown"].includes(intent)) { const below = indicators(c).filter(x => x.status === "abaixo da meta"); push("Quais indicadores estão abaixo da meta?", below.length > 0); push("Analise o absenteísmo.", access.absenteismo === true && (a.mensal ?? []).length > 0); push("Quais ações estão atrasadas?", access.plano_acao === true && (c.acoes ?? []).length > 0); } return out.slice(0, 5); }

function answer(question: string, c: Context, intent: Intent) {
  const a = absRows(c), current = (a.mensal ?? []).find(x => num(x.mes) === num(c.mes)) ?? (a.mensal ?? []).at(-1), previous = (a.mensal ?? []).find(x => num(x.mes) === Math.max(1, num(c.mes) - 1)), inds = indicators(c), below = inds.filter(x => x.status === "abaixo da meta"), actions = c.acoes ?? [], late = actions.filter(x => x.data_fim && new Date(String(x.data_fim)).getTime() < Date.now()), q = `\n\nPergunta analisada: ${question}`, no = (what: string) => `Não há dados suficientes para responder sobre ${what} no contexto autorizado. ${source(c)}`;
  if (intent === "absenteismo") { if (!current) return no("Absenteísmo"); const v = previous ? num(current.indice_absenteismo) - num(previous.indice_absenteismo) : null; const reasons = (a.motivos ?? []).slice(0, 5), areas = (a.areas ?? []).slice(0, 5); return `## Absenteísmo\n${source(c)}\n\nNo período de ${period(c)}, o índice foi ${br(current.indice_absenteismo)}%, com ${br(current.horas_improdutivas)} h improdutivas sobre ${br(current.horas_disponiveis)} h disponíveis. ${v == null ? "Não há mês anterior disponível para comparação." : `A variação contra o mês anterior foi de ${v >= 0 ? "+" : ""}${br(v)} ponto(s) percentual(is).`}\n\n${reasons.length ? `Principais motivos: ${reasons.map(x => `${x.motivo} (${br(x.horas)} h)`).join(", ")}.` : "Não há ranking de motivos disponível."} ${areas.length ? `Maior concentração: ${areas[0].area ?? "não informado"} (${br(areas[0].horas)} h).` : ""}` + q; }
  if (intent === "absenteismo_contribuidores" || intent === "ofensores") { const people = (a.pessoas ?? []).slice(0, 5); return people.length ? `## ${intent === "ofensores" ? "Principais ofensores" : "Quem mais contribuiu"}\n${source(c)}\n\n${people.map((x, i) => `${i + 1}. ${x.colaborador ?? "Não informado"} — ${br(x.horas)} h`).join("; ")}.` + q : no("principais contribuintes"); }
  if (intent === "absenteismo_recorrencia") { const rows = recurring(c); return rows.length ? `## Recorrência\n${source(c)}\n\nForam identificados ${rows.length} colaboradores recorrentes. ${rows.slice(0, 8).map(x => `${x.colaborador ?? "Não informado"} (${br(x.horas)} h em ${x.meses ?? "vários"} mês(es))`).join(", ")}.` + q : no("recorrência"); }
  if (intent === "absenteismo_tendencia") { const months = (a.mensal ?? []).slice().sort((x, y) => num(x.mes) - num(y.mes)); return months.length >= 2 ? `## Tendência de Absenteísmo\n${source(c)}\n\n${months.slice(-3).map(x => `${MONTHS[Math.max(0, num(x.mes) - 1)]}: ${br(x.indice_absenteismo)}%`).join("; ")}.` + q : no("tendência de Absenteísmo"); }
  if (intent === "indicadores_abaixo_meta") return `## Indicadores abaixo da meta\n${source(c)}\n\n${below.length ? `Foram encontrados ${below.length}: ${below.map(x => `${x.name} (${x.result == null ? "sem resultado" : br(x.result)} contra ${br(x.target)})`).join(", ")}.` : "Não foram encontrados indicadores abaixo da meta entre os resultados disponíveis."}` + q;
  if (intent === "indicador_queda") { const declines = indicatorDeclines(c); return declines.length ? `## Quedas e pioras\n${source(c)}\n\n${declines.slice(0, 8).map(x => `${x.indicador} (${br(x.anterior)} → ${br(x.atual)}; variação ${num(x.variacao) >= 0 ? "+" : ""}${br(x.variacao)})`).join("; ")}. A comparação usa os dois últimos resultados disponíveis e não determina a causa.` + q : `## Quedas e pioras\n${source(c)}\n\nNão foram encontrados indicadores que pioraram na comparação com o mês anterior disponível.` + q; }
  if (intent === "acoes_atrasadas") return `## Planos de Ação\n${source(c)}\n\nHá ${actions.length} ação(ões) aberta(s) e ${late.length} com prazo vencido. ${late.length ? late.slice(0, 8).map(x => `${x.acao ?? "ação sem descrição"} (${x.responsavel ?? "não informado"}; prazo ${x.data_fim ?? "sem prazo"}; ${x.status ?? "sem status"})`).join("; ") : "Não há ações vencidas no contexto disponível."}` + q;
  if (intent === "sla_neolog") { if (!(c.sla ?? []).length) return no("SLA NEOLOG"); const points = (c.sla ?? []).filter(x => String(x.tipo ?? "PONTOS") === "PONTOS").reduce((s, x) => s + num(x.valor), 0); return `## SLA NEOLOG\n${source(c)}\n\nHá ${c.sla?.length ?? 0} lançamento(s), totalizando ${br(points)} pontos nos registros disponíveis.` + q; }
  if (intent === "operacao") return `## Operação autorizada\n${source(c)}\n\nO contexto está vinculado exclusivamente a: ${operation(c)}. A resposta respeita o escopo e as permissões do usuário autenticado.` + q;
  return `## Resumo direto\n${source(c)}\n\n${inds.length ? `${inds.filter(x => x.status === "dentro da meta").length} de ${inds.length} indicador(es) dentro da meta.` : "Não há indicadores com resultado."} ${current ? `O Absenteísmo está em ${br(current.indice_absenteismo)}%.` : "Não há registro de Absenteísmo no período."} ${actions.length ? `Existem ${actions.length} ação(ões) aberta(s), sendo ${late.length} vencida(s).` : "Não há ações abertas retornadas."}` + q;
}

async function model(question: string, c: Context, intent: Intent, conversation: Turn[]) { const apiKey = Deno.env.get("OPENAI_API_KEY") ?? Deno.env.get("ASSISTENTE_MODEL_API_KEY"); if (!apiKey) return null; const base = (Deno.env.get("OPENAI_API_BASE") ?? "https://api.openai.com/v1").replace(/\/$/, ""), name = Deno.env.get("ASSISTENTE_MODEL") ?? "gpt-4o-mini"; const r = await fetch(`${base}/chat/completions`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model: name, temperature: 0.1, max_tokens: 900, messages: [{ role: "system", content: `Responda diretamente em português à pergunta atual usando somente o JSON autorizado. Não invente fatos, causas ou números. Intenção: ${intent}.` }, { role: "user", content: JSON.stringify({ pergunta_atual: question, conversa: conversation.slice(-8), contexto: compact(c, intent) }) }] }) }); if (!r.ok) throw new Error(`Modelo indisponível (${r.status})`); const data = await r.json(); return data?.choices?.[0]?.message?.content?.trim() || null; }

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers });
  if (req.method !== "POST") return response({ error: "Método não permitido" }, 405);
  const url = Deno.env.get("SUPABASE_URL"), key = Deno.env.get("SUPABASE_ANON_KEY"), authorization = req.headers.get("Authorization");
  if (!url || !key || !authorization) return response({ error: "Sessão inválida" }, 401);
  const client = createClient(url, key, { global: { headers: { Authorization: authorization } } });
  const token = authorization.replace(/^Bearer\s+/i, "").trim(); const verified = await client.auth.getUser(token); if (verified.error || !verified.data.user) return response({ error: "Sessão inválida" }, 401);
  let body: { question?: string; mode?: string; operation_id?: number | null; year?: number; month?: number | null; module?: string | null; filters?: Record<string, unknown>; conversation?: Turn[] }; try { body = await req.json(); } catch { return response({ error: "JSON inválido" }, 400); }
  const question = String(body.question ?? "").trim(), mode = ["ask", "screen", "monthly"].includes(String(body.mode)) ? String(body.mode) : "ask"; if (question.length > 2000) return response({ error: "Pergunta muito longa" }, 400);
  const operationId = body.operation_id == null ? null : Number(body.operation_id), year = Number(body.year) || new Date().getFullYear(), month = body.month == null ? null : Number(body.month), conversation = Array.isArray(body.conversation) ? body.conversation.filter(x => (x?.role === "user" || x?.role === "assistant") && String(x.content ?? "").length <= 2000).slice(-10) : [], historyQuestion = question || (mode === "monthly" ? "Gerar Análise Executiva do Mês" : "Analisar esta tela");
  const intent = inferIntent(historyQuestion, mode, conversation); const contextQuery = await client.rpc("assistente_obter_conversa_contexto", { p_operacao_id: operationId, p_ano: year, p_mes: month, p_modulo: body.module ?? null, p_filtros: body.filters ?? {} }); if (contextQuery.error) return response({ error: "Não foi possível consultar o contexto autorizado.", code: contextQuery.error.code ?? "ASSISTANT_CONTEXT_ERROR" }, 403); const context = contextQuery.data as Context; if (!context?.permitido) return response({ error: "Você não possui permissão para consultar este contexto." }, 403);
  const history = await client.rpc("assistente_registrar_pergunta", { p_operacao_id: operationId ?? Number(context.operacoes?.[0]?.id), p_modulo: body.module ?? context.modulo ?? "", p_ano: context.ano ?? year, p_mes: context.mes ?? month, p_pergunta: historyQuestion, p_modo: mode }); if (history.error) console.warn("assistant history unavailable", history.error.message);
  const used = records(context, intent.intent), sources = Object.keys(used); let finalAnswer = answer(historyQuestion, context, intent.intent), engine = "analise_deterministica"; try { const generated = await model(historyQuestion, context, intent.intent, conversation); if (generated) { finalAnswer = generated; engine = "modelo_backend"; } } catch (error) { console.warn("assistant model fallback", error instanceof Error ? error.message : error); }
  const next = suggestions(intent.intent, context), trace = { question: historyQuestion, intent: intent.intent, intent_label: intent.label, sources, records_used: used, response: finalAnswer.slice(0, 1500) }; console.info("[Assistente] pergunta → intenção → fontes → registros → resposta", trace);
  return response({ ok: true, answer: finalAnswer, engine, intent: intent.intent, intent_label: intent.label, intent_reason: intent.reason, suggestions: next, sources, records_used: used, context: { header: source(context), operacoes: context.operacoes ?? [], ano: context.ano, mes: context.mes, modulo: context.modulo, acessos: context.acessos ?? {} }, evidence: compact(context, intent.intent), generated_at: new Date().toISOString() });
});
