-- Controle administrativo de usuários, módulos, indicadores e ações.
-- Não recria nem apaga dados de negócio; apenas acrescenta relações e políticas.

CREATE TABLE IF NOT EXISTS public.sustentacao_usuario_modulos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  operacao_id bigint NOT NULL REFERENCES public.sustentacao_operacoes(id) ON DELETE CASCADE,
  modulo text NOT NULL CHECK (modulo IN ('PLANO_SUSTENTACAO','SLA_NEOLOG','ABSENTEISMO','PLANO_ACAO','INVENTARIOS')),
  pode_visualizar boolean NOT NULL DEFAULT false,
  pode_editar boolean NOT NULL DEFAULT false,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sustentacao_usuario_modulos_unique UNIQUE (user_id, operacao_id, modulo),
  CONSTRAINT sustentacao_usuario_modulos_edit_view_check CHECK (pode_editar = false OR pode_visualizar = true)
);

CREATE TABLE IF NOT EXISTS public.sustentacao_usuario_indicadores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  operacao_id bigint NOT NULL REFERENCES public.sustentacao_operacoes(id) ON DELETE CASCADE,
  indicador_id bigint NOT NULL,
  pode_visualizar boolean NOT NULL DEFAULT false,
  pode_editar boolean NOT NULL DEFAULT false,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sustentacao_usuario_indicadores_unique UNIQUE (user_id, operacao_id, indicador_id),
  CONSTRAINT sustentacao_usuario_indicadores_edit_view_check CHECK (pode_editar = false OR pode_visualizar = true)
);

CREATE TABLE IF NOT EXISTS public.sustentacao_usuario_plano_acao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  operacao_id bigint NOT NULL REFERENCES public.sustentacao_operacoes(id) ON DELETE CASCADE,
  pode_visualizar boolean NOT NULL DEFAULT false,
  pode_criar boolean NOT NULL DEFAULT false,
  pode_editar boolean NOT NULL DEFAULT false,
  pode_alterar_status boolean NOT NULL DEFAULT false,
  pode_concluir boolean NOT NULL DEFAULT false,
  pode_excluir boolean NOT NULL DEFAULT false,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sustentacao_usuario_plano_acao_unique UNIQUE (user_id, operacao_id),
  CONSTRAINT sustentacao_usuario_plano_acao_view_check CHECK (
    pode_visualizar = true OR NOT (pode_criar OR pode_editar OR pode_alterar_status OR pode_concluir OR pode_excluir)
  )
);

CREATE TABLE IF NOT EXISTS public.sustentacao_auditoria_permissoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ator_user_id uuid NOT NULL REFERENCES auth.users(id),
  alvo_user_id uuid NOT NULL REFERENCES auth.users(id),
  operacao_id bigint REFERENCES public.sustentacao_operacoes(id),
  tipo_alteracao text NOT NULL,
  permissoes_anteriores jsonb NOT NULL DEFAULT '{}'::jsonb,
  permissoes_novas jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.sustentacao_plano_acao
  ADD COLUMN IF NOT EXISTS indicador_id bigint,
  ADD COLUMN IF NOT EXISTS responsavel_user_id uuid;

ALTER TABLE public.sustentacao_sla_neolog_pontuacoes
  ADD COLUMN IF NOT EXISTS indicador_id bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sustentacao_indicadores_id_operacao_key'
      AND conrelid = 'public.sustentacao_indicadores'::regclass
  ) THEN
    ALTER TABLE public.sustentacao_indicadores
      ADD CONSTRAINT sustentacao_indicadores_id_operacao_key UNIQUE (id, operacao_id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sustentacao_resultados_id_operacao_key'
      AND conrelid = 'public.sustentacao_resultados'::regclass
  ) THEN
    ALTER TABLE public.sustentacao_resultados
      ADD CONSTRAINT sustentacao_resultados_id_operacao_key UNIQUE (id, operacao_id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sustentacao_usuario_indicadores_indicator_operation_fkey'
      AND conrelid = 'public.sustentacao_usuario_indicadores'::regclass
  ) THEN
    ALTER TABLE public.sustentacao_usuario_indicadores
      ADD CONSTRAINT sustentacao_usuario_indicadores_indicator_operation_fkey
      FOREIGN KEY (indicador_id, operacao_id)
      REFERENCES public.sustentacao_indicadores (id, operacao_id)
      ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sustentacao_plano_acao_indicator_operation_fkey'
      AND conrelid = 'public.sustentacao_plano_acao'::regclass
  ) THEN
    ALTER TABLE public.sustentacao_plano_acao
      ADD CONSTRAINT sustentacao_plano_acao_indicator_operation_fkey
      FOREIGN KEY (indicador_id, operacao_id)
      REFERENCES public.sustentacao_indicadores (id, operacao_id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sustentacao_plano_acao_responsavel_user_fkey'
      AND conrelid = 'public.sustentacao_plano_acao'::regclass
  ) THEN
    ALTER TABLE public.sustentacao_plano_acao
      ADD CONSTRAINT sustentacao_plano_acao_responsavel_user_fkey
      FOREIGN KEY (responsavel_user_id)
      REFERENCES auth.users (id)
      ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sustentacao_sla_indicator_operation_fkey'
      AND conrelid = 'public.sustentacao_sla_neolog_pontuacoes'::regclass
  ) THEN
    ALTER TABLE public.sustentacao_sla_neolog_pontuacoes
      ADD CONSTRAINT sustentacao_sla_indicator_operation_fkey
      FOREIGN KEY (indicador_id, operacao_id)
      REFERENCES public.sustentacao_indicadores (id, operacao_id);
  END IF;
END $$;

-- Liga as linhas SLA existentes aos indicadores GLP sem alterar ano, mês, tipo ou valor.
UPDATE public.sustentacao_sla_neolog_pontuacoes s
SET indicador_id = i.id,
    updated_at = now()
FROM public.sustentacao_indicadores i
WHERE s.operacao_id = i.operacao_id
  AND i.operacao_id = (SELECT id FROM public.sustentacao_operacoes WHERE codigo = 'GLP_ACHE' LIMIT 1)
  AND i.nome = CASE
    WHEN s.indicador = 'Ocorrências Fora do Prazo' THEN 'Ocorrências Monitoramento'
    ELSE s.indicador
  END
  AND s.indicador_id IS NULL;

CREATE INDEX IF NOT EXISTS sustentacao_usuario_modulos_user_operation_idx
  ON public.sustentacao_usuario_modulos (user_id, operacao_id);
CREATE INDEX IF NOT EXISTS sustentacao_usuario_indicadores_user_operation_idx
  ON public.sustentacao_usuario_indicadores (user_id, operacao_id);
CREATE INDEX IF NOT EXISTS sustentacao_usuario_indicadores_indicator_idx
  ON public.sustentacao_usuario_indicadores (indicador_id, operacao_id);
CREATE INDEX IF NOT EXISTS sustentacao_usuario_plano_acao_user_operation_idx
  ON public.sustentacao_usuario_plano_acao (user_id, operacao_id);
CREATE INDEX IF NOT EXISTS sustentacao_auditoria_permissoes_target_idx
  ON public.sustentacao_auditoria_permissoes (alvo_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sustentacao_sla_indicator_operation_idx
  ON public.sustentacao_sla_neolog_pontuacoes (indicador_id, operacao_id);

CREATE OR REPLACE FUNCTION public.eh_admin_sustentacao()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.sustentacao_usuarios su
    WHERE su.user_id = (SELECT auth.uid())
      AND su.ativo = true
      AND su.perfil = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.tem_acesso_operacao(p_operacao_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.eh_admin_sustentacao()
      OR EXISTS (
        SELECT 1
        FROM public.sustentacao_usuarios su
        JOIN public.sustentacao_usuario_operacoes suo ON suo.user_id = su.user_id
        WHERE su.user_id = (SELECT auth.uid())
          AND su.ativo = true
          AND suo.ativo = true
          AND suo.operacao_id = p_operacao_id
      );
$$;

CREATE OR REPLACE FUNCTION public.tem_acesso_modulo(p_operacao_id bigint, p_modulo text, p_acao text DEFAULT 'VIEW')
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.eh_admin_sustentacao()
      OR EXISTS (
        SELECT 1
        FROM public.sustentacao_usuario_modulos m
        JOIN public.sustentacao_usuarios su ON su.user_id = m.user_id
        WHERE m.user_id = (SELECT auth.uid())
          AND su.ativo = true
          AND m.operacao_id = p_operacao_id
          AND m.modulo = upper(p_modulo)
          AND m.ativo = true
          AND CASE upper(coalesce(p_acao, 'VIEW'))
                WHEN 'EDIT' THEN m.pode_editar
                ELSE m.pode_visualizar
              END
      );
$$;

CREATE OR REPLACE FUNCTION public.tem_acesso_indicador(p_operacao_id bigint, p_indicador_id bigint, p_acao text DEFAULT 'VIEW')
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.eh_admin_sustentacao()
      OR EXISTS (
        SELECT 1
        FROM public.sustentacao_usuario_indicadores ui
        JOIN public.sustentacao_usuarios su ON su.user_id = ui.user_id
        WHERE ui.user_id = (SELECT auth.uid())
          AND su.ativo = true
          AND ui.operacao_id = p_operacao_id
          AND ui.indicador_id = p_indicador_id
          AND ui.ativo = true
          AND CASE upper(coalesce(p_acao, 'VIEW'))
                WHEN 'EDIT' THEN ui.pode_editar
                ELSE ui.pode_visualizar
              END
      );
$$;

CREATE OR REPLACE FUNCTION public.tem_acesso_inventario(p_operacao_id bigint, p_resultado_id bigint, p_acao text DEFAULT 'VIEW')
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.eh_admin_sustentacao()
      OR (
        public.tem_acesso_modulo(p_operacao_id, 'INVENTARIOS', p_acao)
        AND EXISTS (
          SELECT 1
          FROM public.sustentacao_resultados r
          WHERE r.id = p_resultado_id
            AND r.operacao_id = p_operacao_id
            AND public.tem_acesso_indicador(p_operacao_id, r.indicador_id, p_acao)
        )
      );
$$;

CREATE OR REPLACE FUNCTION public.tem_acesso_plano_acao(p_operacao_id bigint, p_indicador_id bigint, p_acao text DEFAULT 'VIEW')
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.eh_admin_sustentacao()
      OR (
        EXISTS (
          SELECT 1
          FROM public.sustentacao_usuario_plano_acao pa
          JOIN public.sustentacao_usuarios su ON su.user_id = pa.user_id
          WHERE pa.user_id = (SELECT auth.uid())
            AND su.ativo = true
            AND pa.operacao_id = p_operacao_id
            AND pa.ativo = true
            AND CASE upper(coalesce(p_acao, 'VIEW'))
                  WHEN 'CREATE' THEN pa.pode_criar
                  WHEN 'EDIT' THEN pa.pode_editar
                  WHEN 'STATUS' THEN pa.pode_alterar_status
                  WHEN 'CONCLUDE' THEN pa.pode_concluir
                  WHEN 'DELETE' THEN pa.pode_excluir
                  ELSE pa.pode_visualizar
                END
        )
        AND (
          p_indicador_id IS NULL
          OR public.tem_acesso_indicador(p_operacao_id, p_indicador_id, CASE WHEN upper(coalesce(p_acao, 'VIEW')) = 'VIEW' THEN 'VIEW' ELSE 'EDIT' END)
        )
      );
$$;

CREATE OR REPLACE FUNCTION public.tem_acesso_operacao_visualizacao(p_operacao_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.eh_admin_sustentacao()
      OR (
        public.tem_acesso_operacao(p_operacao_id)
        AND EXISTS (
          SELECT 1 FROM public.sustentacao_usuario_modulos m
          WHERE m.user_id = (SELECT auth.uid())
            AND m.operacao_id = p_operacao_id
            AND m.ativo = true
            AND m.pode_visualizar = true
        )
      );
$$;

-- Função transacional usada pela tela administrativa para gravar o perfil e todas as permissões.
CREATE OR REPLACE FUNCTION public.admin_save_user_access(
  p_user_id uuid,
  p_email text,
  p_nome text,
  p_perfil text,
  p_ativo boolean,
  p_operation_ids bigint[] DEFAULT '{}'::bigint[],
  p_module_permissions jsonb DEFAULT '[]'::jsonb,
  p_indicator_permissions jsonb DEFAULT '[]'::jsonb,
  p_action_permissions jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old public.sustentacao_usuarios%ROWTYPE;
  v_found boolean := false;
  v_old_snapshot jsonb;
  v_new_snapshot jsonb;
  v_operation_ids bigint[] := coalesce(p_operation_ids, '{}'::bigint[]);
  v_other_admins integer;
BEGIN
  IF NOT public.eh_admin_sustentacao() THEN
    RAISE EXCEPTION 'Apenas Administrador pode alterar usuários e permissões';
  END IF;
  IF p_user_id IS NULL OR NOT EXISTS (SELECT 1 FROM auth.users au WHERE au.id = p_user_id) THEN
    RAISE EXCEPTION 'Usuário Auth inexistente';
  END IF;
  IF lower(coalesce(p_perfil, '')) NOT IN ('admin','gestor','usuario') THEN
    RAISE EXCEPTION 'Perfil inválido';
  END IF;
  SELECT * INTO v_old FROM public.sustentacao_usuarios WHERE user_id = p_user_id;
  v_found := FOUND;
  IF v_found AND lower(v_old.email) <> lower(trim(p_email)) THEN
    RAISE EXCEPTION 'O e-mail Auth não pode ser alterado por esta rotina';
  END IF;
  IF v_found AND v_old.perfil = 'admin' AND v_old.ativo = true AND (lower(p_perfil) <> 'admin' OR p_ativo = false) THEN
    SELECT count(*) INTO v_other_admins
    FROM public.sustentacao_usuarios
    WHERE perfil = 'admin' AND ativo = true AND user_id <> p_user_id;
    IF v_other_admins = 0 THEN
      RAISE EXCEPTION 'Não é permitido desativar ou rebaixar o último Administrador ativo';
    END IF;
  END IF;

  SELECT jsonb_build_object(
    'perfil', v_old.perfil,
    'ativo', v_old.ativo,
    'operacoes', coalesce((SELECT jsonb_agg(suo.operacao_id ORDER BY suo.operacao_id) FROM public.sustentacao_usuario_operacoes suo WHERE suo.user_id=p_user_id), '[]'::jsonb),
    'modulos', coalesce((SELECT jsonb_agg(jsonb_build_object('operacao_id',m.operacao_id,'modulo',m.modulo,'pode_visualizar',m.pode_visualizar,'pode_editar',m.pode_editar,'ativo',m.ativo) ORDER BY m.id) FROM public.sustentacao_usuario_modulos m WHERE m.user_id=p_user_id), '[]'::jsonb),
    'indicadores', coalesce((SELECT jsonb_agg(jsonb_build_object('operacao_id',i.operacao_id,'indicador_id',i.indicador_id,'pode_visualizar',i.pode_visualizar,'pode_editar',i.pode_editar,'ativo',i.ativo) ORDER BY i.id) FROM public.sustentacao_usuario_indicadores i WHERE i.user_id=p_user_id), '[]'::jsonb),
    'plano_acao', coalesce((SELECT jsonb_agg(to_jsonb(pa) - 'id' - 'user_id' ORDER BY pa.id) FROM public.sustentacao_usuario_plano_acao pa WHERE pa.user_id=p_user_id), '[]'::jsonb)
  ) INTO v_old_snapshot;

  INSERT INTO public.sustentacao_usuarios (user_id,email,nome,perfil,ativo,updated_at)
  VALUES (p_user_id,trim(lower(p_email)),nullif(trim(p_nome),''),lower(p_perfil),p_ativo,now())
  ON CONFLICT (user_id) DO UPDATE SET
    email=excluded.email,
    nome=excluded.nome,
    perfil=excluded.perfil,
    ativo=excluded.ativo,
    updated_at=now();

  IF lower(p_perfil) = 'admin' THEN
    SELECT coalesce(array_agg(id ORDER BY id), '{}'::bigint[]) INTO v_operation_ids
    FROM public.sustentacao_operacoes WHERE ativo = true;
  END IF;

  DELETE FROM public.sustentacao_usuario_operacoes WHERE user_id=p_user_id;
  INSERT INTO public.sustentacao_usuario_operacoes (user_id,operacao_id,ativo,updated_at)
  SELECT p_user_id,x,true,now() FROM unnest(v_operation_ids) AS x;

  DELETE FROM public.sustentacao_usuario_modulos WHERE user_id=p_user_id;
  INSERT INTO public.sustentacao_usuario_modulos (user_id,operacao_id,modulo,pode_visualizar,pode_editar,ativo,updated_at)
  SELECT p_user_id,x.operacao_id,upper(x.modulo),coalesce(x.pode_visualizar,false),coalesce(x.pode_editar,false),true,now()
  FROM jsonb_to_recordset(coalesce(p_module_permissions,'[]'::jsonb)) AS x(operacao_id bigint,modulo text,pode_visualizar boolean,pode_editar boolean)
  WHERE x.operacao_id = ANY(v_operation_ids);

  DELETE FROM public.sustentacao_usuario_indicadores WHERE user_id=p_user_id;
  INSERT INTO public.sustentacao_usuario_indicadores (user_id,operacao_id,indicador_id,pode_visualizar,pode_editar,ativo,updated_at)
  SELECT p_user_id,x.operacao_id,x.indicador_id,coalesce(x.pode_visualizar,false),coalesce(x.pode_editar,false),true,now()
  FROM jsonb_to_recordset(coalesce(p_indicator_permissions,'[]'::jsonb)) AS x(operacao_id bigint,indicador_id bigint,pode_visualizar boolean,pode_editar boolean)
  WHERE x.operacao_id = ANY(v_operation_ids)
    AND EXISTS (SELECT 1 FROM public.sustentacao_indicadores i WHERE i.id=x.indicador_id AND i.operacao_id=x.operacao_id);

  DELETE FROM public.sustentacao_usuario_plano_acao WHERE user_id=p_user_id;
  INSERT INTO public.sustentacao_usuario_plano_acao (user_id,operacao_id,pode_visualizar,pode_criar,pode_editar,pode_alterar_status,pode_concluir,pode_excluir,ativo,updated_at)
  SELECT p_user_id,x.operacao_id,coalesce(x.pode_visualizar,false),coalesce(x.pode_criar,false),coalesce(x.pode_editar,false),coalesce(x.pode_alterar_status,false),coalesce(x.pode_concluir,false),coalesce(x.pode_excluir,false),true,now()
  FROM jsonb_to_recordset(coalesce(p_action_permissions,'[]'::jsonb)) AS x(operacao_id bigint,pode_visualizar boolean,pode_criar boolean,pode_editar boolean,pode_alterar_status boolean,pode_concluir boolean,pode_excluir boolean)
  WHERE x.operacao_id = ANY(v_operation_ids);

  SELECT jsonb_build_object(
    'perfil', lower(p_perfil),
    'ativo', p_ativo,
    'operacoes', to_jsonb(v_operation_ids),
    'modulos', coalesce((SELECT jsonb_agg(jsonb_build_object('operacao_id',m.operacao_id,'modulo',m.modulo,'pode_visualizar',m.pode_visualizar,'pode_editar',m.pode_editar,'ativo',m.ativo) ORDER BY m.id) FROM public.sustentacao_usuario_modulos m WHERE m.user_id=p_user_id), '[]'::jsonb),
    'indicadores', coalesce((SELECT jsonb_agg(jsonb_build_object('operacao_id',i.operacao_id,'indicador_id',i.indicador_id,'pode_visualizar',i.pode_visualizar,'pode_editar',i.pode_editar,'ativo',i.ativo) ORDER BY i.id) FROM public.sustentacao_usuario_indicadores i WHERE i.user_id=p_user_id), '[]'::jsonb),
    'plano_acao', coalesce((SELECT jsonb_agg(to_jsonb(pa) - 'id' - 'user_id' ORDER BY pa.id) FROM public.sustentacao_usuario_plano_acao pa WHERE pa.user_id=p_user_id), '[]'::jsonb)
  ) INTO v_new_snapshot;

  INSERT INTO public.sustentacao_auditoria_permissoes (ator_user_id,alvo_user_id,tipo_alteracao,permissoes_anteriores,permissoes_novas)
  VALUES ((SELECT auth.uid()),p_user_id,CASE WHEN v_found THEN 'ATUALIZACAO_USUARIO_PERMISSOES' ELSE 'CADASTRO_USUARIO_PERMISSOES' END,coalesce(v_old_snapshot,'{}'::jsonb),v_new_snapshot);

  RETURN jsonb_build_object('ok',true,'user_id',p_user_id);
END;
$$;

REVOKE ALL ON FUNCTION public.admin_save_user_access(uuid,text,text,text,boolean,bigint[],jsonb,jsonb,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_save_user_access(uuid,text,text,text,boolean,bigint[],jsonb,jsonb,jsonb) TO authenticated;

ALTER TABLE public.sustentacao_usuario_modulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustentacao_usuario_indicadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustentacao_usuario_plano_acao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustentacao_auditoria_permissoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sustentacao_usuario_modulos_admin ON public.sustentacao_usuario_modulos;
DROP POLICY IF EXISTS sustentacao_usuario_modulos_self ON public.sustentacao_usuario_modulos;
CREATE POLICY sustentacao_usuario_modulos_admin ON public.sustentacao_usuario_modulos FOR SELECT TO authenticated USING (public.eh_admin_sustentacao());
CREATE POLICY sustentacao_usuario_modulos_self ON public.sustentacao_usuario_modulos FOR SELECT TO authenticated USING (user_id=(SELECT auth.uid()));

DROP POLICY IF EXISTS sustentacao_usuario_indicadores_admin ON public.sustentacao_usuario_indicadores;
DROP POLICY IF EXISTS sustentacao_usuario_indicadores_self ON public.sustentacao_usuario_indicadores;
CREATE POLICY sustentacao_usuario_indicadores_admin ON public.sustentacao_usuario_indicadores FOR SELECT TO authenticated USING (public.eh_admin_sustentacao());
CREATE POLICY sustentacao_usuario_indicadores_self ON public.sustentacao_usuario_indicadores FOR SELECT TO authenticated USING (user_id=(SELECT auth.uid()));

DROP POLICY IF EXISTS sustentacao_usuario_plano_acao_admin ON public.sustentacao_usuario_plano_acao;
DROP POLICY IF EXISTS sustentacao_usuario_plano_acao_self ON public.sustentacao_usuario_plano_acao;
CREATE POLICY sustentacao_usuario_plano_acao_admin ON public.sustentacao_usuario_plano_acao FOR SELECT TO authenticated USING (public.eh_admin_sustentacao());
CREATE POLICY sustentacao_usuario_plano_acao_self ON public.sustentacao_usuario_plano_acao FOR SELECT TO authenticated USING (user_id=(SELECT auth.uid()));

DROP POLICY IF EXISTS sustentacao_auditoria_permissoes_admin ON public.sustentacao_auditoria_permissoes;
CREATE POLICY sustentacao_auditoria_permissoes_admin ON public.sustentacao_auditoria_permissoes FOR SELECT TO authenticated USING (public.eh_admin_sustentacao());

DROP POLICY IF EXISTS sustentacao_usuarios_admin_gerencia ON public.sustentacao_usuarios;
DROP POLICY IF EXISTS admin_gerencia_usuarios ON public.sustentacao_usuarios;
DROP POLICY IF EXISTS usuario_visualiza_proprio_cadastro ON public.sustentacao_usuarios;
CREATE POLICY sustentacao_usuarios_admin_select ON public.sustentacao_usuarios FOR SELECT TO authenticated USING (public.eh_admin_sustentacao());
CREATE POLICY sustentacao_usuarios_self_select ON public.sustentacao_usuarios FOR SELECT TO authenticated USING (user_id=(SELECT auth.uid()));

DROP POLICY IF EXISTS sustentacao_usuario_operacoes_acesso ON public.sustentacao_usuario_operacoes;
CREATE POLICY sustentacao_usuario_operacoes_admin_select ON public.sustentacao_usuario_operacoes FOR SELECT TO authenticated USING (public.eh_admin_sustentacao());
CREATE POLICY sustentacao_usuario_operacoes_self_select ON public.sustentacao_usuario_operacoes FOR SELECT TO authenticated USING (user_id=(SELECT auth.uid()));

DROP POLICY IF EXISTS sustentacao_operacoes_acesso ON public.sustentacao_operacoes;
CREATE POLICY sustentacao_operacoes_acesso ON public.sustentacao_operacoes FOR SELECT TO authenticated USING (public.tem_acesso_operacao_visualizacao(id));

DROP POLICY IF EXISTS sustentacao_indicadores_acesso ON public.sustentacao_indicadores;
CREATE POLICY sustentacao_indicadores_select ON public.sustentacao_indicadores FOR SELECT TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','VIEW') AND public.tem_acesso_indicador(operacao_id,id,'VIEW'));
CREATE POLICY sustentacao_indicadores_insert ON public.sustentacao_indicadores FOR INSERT TO authenticated WITH CHECK (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,id,'EDIT'));
CREATE POLICY sustentacao_indicadores_update ON public.sustentacao_indicadores FOR UPDATE TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,id,'EDIT')) WITH CHECK (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,id,'EDIT'));
CREATE POLICY sustentacao_indicadores_delete ON public.sustentacao_indicadores FOR DELETE TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,id,'EDIT'));

DROP POLICY IF EXISTS sustentacao_resultados_acesso ON public.sustentacao_resultados;
CREATE POLICY sustentacao_resultados_select ON public.sustentacao_resultados FOR SELECT TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','VIEW') AND public.tem_acesso_indicador(operacao_id,indicador_id,'VIEW'));
CREATE POLICY sustentacao_resultados_insert ON public.sustentacao_resultados FOR INSERT TO authenticated WITH CHECK (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));
CREATE POLICY sustentacao_resultados_update ON public.sustentacao_resultados FOR UPDATE TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT')) WITH CHECK (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));
CREATE POLICY sustentacao_resultados_delete ON public.sustentacao_resultados FOR DELETE TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));

DROP POLICY IF EXISTS sustentacao_inventarios_acesso ON public.sustentacao_inventarios;
CREATE POLICY sustentacao_inventarios_select ON public.sustentacao_inventarios FOR SELECT TO authenticated USING (public.tem_acesso_inventario(operacao_id,resultado_id,'VIEW'));
CREATE POLICY sustentacao_inventarios_insert ON public.sustentacao_inventarios FOR INSERT TO authenticated WITH CHECK (public.tem_acesso_inventario(operacao_id,resultado_id,'EDIT'));
CREATE POLICY sustentacao_inventarios_update ON public.sustentacao_inventarios FOR UPDATE TO authenticated USING (public.tem_acesso_inventario(operacao_id,resultado_id,'EDIT')) WITH CHECK (public.tem_acesso_inventario(operacao_id,resultado_id,'EDIT'));
CREATE POLICY sustentacao_inventarios_delete ON public.sustentacao_inventarios FOR DELETE TO authenticated USING (public.tem_acesso_inventario(operacao_id,resultado_id,'EDIT'));

DROP POLICY IF EXISTS sustentacao_plano_acao_acesso ON public.sustentacao_plano_acao;
CREATE POLICY sustentacao_plano_acao_select ON public.sustentacao_plano_acao FOR SELECT TO authenticated USING (public.tem_acesso_plano_acao(operacao_id,indicador_id,'VIEW'));
CREATE POLICY sustentacao_plano_acao_insert ON public.sustentacao_plano_acao FOR INSERT TO authenticated WITH CHECK (public.tem_acesso_plano_acao(operacao_id,indicador_id,'CREATE'));
CREATE POLICY sustentacao_plano_acao_update ON public.sustentacao_plano_acao FOR UPDATE TO authenticated USING (public.tem_acesso_plano_acao(operacao_id,indicador_id,'EDIT')) WITH CHECK (public.tem_acesso_plano_acao(operacao_id,indicador_id,'EDIT'));
CREATE POLICY sustentacao_plano_acao_delete ON public.sustentacao_plano_acao FOR DELETE TO authenticated USING (public.tem_acesso_plano_acao(operacao_id,indicador_id,'DELETE'));

DROP POLICY IF EXISTS sustentacao_sla_neolog_pontuacoes_acesso ON public.sustentacao_sla_neolog_pontuacoes;
CREATE POLICY sustentacao_sla_neolog_select ON public.sustentacao_sla_neolog_pontuacoes FOR SELECT TO authenticated USING (public.tem_acesso_modulo(operacao_id,'SLA_NEOLOG','VIEW') AND public.tem_acesso_indicador(operacao_id,indicador_id,'VIEW'));
CREATE POLICY sustentacao_sla_neolog_insert ON public.sustentacao_sla_neolog_pontuacoes FOR INSERT TO authenticated WITH CHECK (public.tem_acesso_modulo(operacao_id,'SLA_NEOLOG','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));
CREATE POLICY sustentacao_sla_neolog_update ON public.sustentacao_sla_neolog_pontuacoes FOR UPDATE TO authenticated USING (public.tem_acesso_modulo(operacao_id,'SLA_NEOLOG','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT')) WITH CHECK (public.tem_acesso_modulo(operacao_id,'SLA_NEOLOG','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));
CREATE POLICY sustentacao_sla_neolog_delete ON public.sustentacao_sla_neolog_pontuacoes FOR DELETE TO authenticated USING (public.tem_acesso_modulo(operacao_id,'SLA_NEOLOG','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));

DROP POLICY IF EXISTS absenteismo_areas_acesso ON public.absenteismo_areas;
CREATE POLICY absenteismo_areas_acesso ON public.absenteismo_areas FOR ALL TO authenticated USING (public.tem_acesso_modulo(operacao_id,'ABSENTEISMO','VIEW')) WITH CHECK (public.tem_acesso_modulo(operacao_id,'ABSENTEISMO','EDIT'));
DROP POLICY IF EXISTS absenteismo_registros_acesso ON public.absenteismo_registros;
CREATE POLICY absenteismo_registros_acesso ON public.absenteismo_registros FOR ALL TO authenticated USING (public.tem_acesso_modulo(operacao_id,'ABSENTEISMO','VIEW')) WITH CHECK (public.tem_acesso_modulo(operacao_id,'ABSENTEISMO','EDIT'));
DROP POLICY IF EXISTS absenteismo_resumo_acesso ON public.absenteismo_resumo_mensal;
CREATE POLICY absenteismo_resumo_acesso ON public.absenteismo_resumo_mensal FOR ALL TO authenticated USING (public.eh_admin_sustentacao() OR public.tem_acesso_modulo(operacao_id,'ABSENTEISMO','VIEW')) WITH CHECK (public.eh_admin_sustentacao() OR public.tem_acesso_modulo(operacao_id,'ABSENTEISMO','EDIT'));
DROP POLICY IF EXISTS absenteismo_analise_acesso ON public.absenteismo_analise_colaborador;
CREATE POLICY absenteismo_analise_acesso ON public.absenteismo_analise_colaborador FOR ALL TO authenticated USING (public.eh_admin_sustentacao() OR public.tem_acesso_modulo(operacao_id,'ABSENTEISMO','VIEW')) WITH CHECK (public.eh_admin_sustentacao() OR public.tem_acesso_modulo(operacao_id,'ABSENTEISMO','EDIT'));

DROP POLICY IF EXISTS sustentacao_detalhes_acesso ON public.sustentacao_detalhes;
CREATE POLICY sustentacao_detalhes_select ON public.sustentacao_detalhes FOR SELECT TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','VIEW') AND public.tem_acesso_indicador(operacao_id,indicador_id,'VIEW'));
CREATE POLICY sustentacao_detalhes_insert ON public.sustentacao_detalhes FOR INSERT TO authenticated WITH CHECK (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));
CREATE POLICY sustentacao_detalhes_update ON public.sustentacao_detalhes FOR UPDATE TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT')) WITH CHECK (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));
CREATE POLICY sustentacao_detalhes_delete ON public.sustentacao_detalhes FOR DELETE TO authenticated USING (public.tem_acesso_modulo(operacao_id,'PLANO_SUSTENTACAO','EDIT') AND public.tem_acesso_indicador(operacao_id,indicador_id,'EDIT'));

GRANT SELECT ON public.sustentacao_usuario_modulos, public.sustentacao_usuario_indicadores, public.sustentacao_usuario_plano_acao, public.sustentacao_auditoria_permissoes TO authenticated;
