-- Assistente de Gestão V1: permissões dedicadas, contexto autorizado, histórico e RLS.
-- Migration aditiva: não altera indicadores, resultados, Absenteísmo ou planos existentes.

CREATE TABLE IF NOT EXISTS public.sustentacao_assistente_permissoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  operacao_id bigint REFERENCES public.sustentacao_operacoes(id) ON DELETE CASCADE,
  pode_acessar boolean NOT NULL DEFAULT false,
  pode_consultar_indicadores boolean NOT NULL DEFAULT false,
  pode_consultar_absenteismo boolean NOT NULL DEFAULT false,
  pode_consultar_plano_acao boolean NOT NULL DEFAULT false,
  pode_consultar_sla_neolog boolean NOT NULL DEFAULT false,
  pode_consultar_visao_executiva boolean NOT NULL DEFAULT false,
  pode_analisar_consolidado boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS sustentacao_assistente_permissoes_user_scope_uidx
  ON public.sustentacao_assistente_permissoes (user_id, coalesce(operacao_id, 0));
CREATE INDEX IF NOT EXISTS sustentacao_assistente_permissoes_scope_idx
  ON public.sustentacao_assistente_permissoes (operacao_id, user_id)
  WHERE pode_acessar = true;

CREATE TABLE IF NOT EXISTS public.sustentacao_assistente_historico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  operacao_id bigint REFERENCES public.sustentacao_operacoes(id) ON DELETE SET NULL,
  modulo text,
  ano integer,
  mes integer,
  pergunta text NOT NULL,
  modo text NOT NULL DEFAULT 'ask',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sustentacao_assistente_historico_mes_check CHECK (mes IS NULL OR mes BETWEEN 1 AND 12),
  CONSTRAINT sustentacao_assistente_historico_modo_check CHECK (modo IN ('ask','screen','monthly'))
);
CREATE INDEX IF NOT EXISTS sustentacao_assistente_historico_user_created_idx
  ON public.sustentacao_assistente_historico (user_id, created_at DESC);

ALTER TABLE public.sustentacao_assistente_permissoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustentacao_assistente_historico ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sustentacao_assistente_permissoes_select ON public.sustentacao_assistente_permissoes;
CREATE POLICY sustentacao_assistente_permissoes_select ON public.sustentacao_assistente_permissoes
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    OR (operacao_id IS NULL AND public.eh_super_admin())
    OR (operacao_id IS NOT NULL AND public.tem_acesso_admin_usuario(user_id, operacao_id))
  );

DROP POLICY IF EXISTS sustentacao_assistente_permissoes_insert ON public.sustentacao_assistente_permissoes;
CREATE POLICY sustentacao_assistente_permissoes_insert ON public.sustentacao_assistente_permissoes
  FOR INSERT TO authenticated
  WITH CHECK (
    (operacao_id IS NULL AND public.eh_super_admin())
    OR (operacao_id IS NOT NULL AND public.tem_acesso_admin_usuario(user_id, operacao_id))
  );

DROP POLICY IF EXISTS sustentacao_assistente_permissoes_update ON public.sustentacao_assistente_permissoes;
CREATE POLICY sustentacao_assistente_permissoes_update ON public.sustentacao_assistente_permissoes
  FOR UPDATE TO authenticated
  USING (
    (operacao_id IS NULL AND public.eh_super_admin())
    OR (operacao_id IS NOT NULL AND public.tem_acesso_admin_usuario(user_id, operacao_id))
  )
  WITH CHECK (
    (operacao_id IS NULL AND public.eh_super_admin())
    OR (operacao_id IS NOT NULL AND public.tem_acesso_admin_usuario(user_id, operacao_id))
  );

DROP POLICY IF EXISTS sustentacao_assistente_permissoes_delete ON public.sustentacao_assistente_permissoes;
CREATE POLICY sustentacao_assistente_permissoes_delete ON public.sustentacao_assistente_permissoes
  FOR DELETE TO authenticated
  USING (
    (operacao_id IS NULL AND public.eh_super_admin())
    OR (operacao_id IS NOT NULL AND public.tem_acesso_admin_usuario(user_id, operacao_id))
  );

DROP POLICY IF EXISTS sustentacao_assistente_historico_self_select ON public.sustentacao_assistente_historico;
CREATE POLICY sustentacao_assistente_historico_self_select ON public.sustentacao_assistente_historico
  FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.eh_super_admin());
DROP POLICY IF EXISTS sustentacao_assistente_historico_self_insert ON public.sustentacao_assistente_historico;
CREATE POLICY sustentacao_assistente_historico_self_insert ON public.sustentacao_assistente_historico
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.assistente_tem_permissao(
  p_operacao_id bigint,
  p_capacidade text DEFAULT 'acessar'
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN auth.uid() IS NULL THEN false
    WHEN public.eh_super_admin() THEN true
    ELSE EXISTS (
      SELECT 1
      FROM public.sustentacao_assistente_permissoes p
      JOIN public.sustentacao_usuarios su ON su.user_id = p.user_id AND su.ativo = true
      WHERE p.user_id = auth.uid()
        AND p.operacao_id = p_operacao_id
        AND p.pode_acessar = true
        AND CASE lower(coalesce(p_capacidade, 'acessar'))
          WHEN 'acessar' THEN p.pode_acessar
          WHEN 'indicadores' THEN p.pode_consultar_indicadores
          WHEN 'absenteismo' THEN p.pode_consultar_absenteismo
          WHEN 'plano_acao' THEN p.pode_consultar_plano_acao
          WHEN 'sla_neolog' THEN p.pode_consultar_sla_neolog
          WHEN 'visao_executiva' THEN p.pode_consultar_visao_executiva
          WHEN 'consolidado' THEN p.pode_analisar_consolidado
          ELSE false
        END
    )
  END;
$$;

CREATE OR REPLACE FUNCTION public.admin_save_assistant_access(
  p_user_id uuid,
  p_permissions jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := auth.uid();
  is_super boolean := public.eh_super_admin();
  allowed_scope bigint[];
BEGIN
  IF actor IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.sustentacao_usuarios
    WHERE user_id = actor AND ativo = true
  ) THEN
    RAISE EXCEPTION 'Sessão sem usuário operacional ativo';
  END IF;
  IF NOT is_super AND NOT public.tem_acesso_central_administrativa() THEN
    RAISE EXCEPTION 'Usuário sem permissão para administrar a Central';
  END IF;
  IF p_user_id IS NULL OR NOT EXISTS (SELECT 1 FROM auth.users WHERE id = p_user_id) THEN
    RAISE EXCEPTION 'Usuário Auth inexistente';
  END IF;
  IF NOT is_super AND NOT public.tem_acesso_admin_usuario(p_user_id) THEN
    RAISE EXCEPTION 'Usuário fora do escopo operacional do administrador';
  END IF;

  SELECT coalesce(array_agg(o.id ORDER BY o.id), '{}')
    INTO allowed_scope
  FROM public.sustentacao_operacoes o
  WHERE o.ativo = true
    AND (is_super OR public.tem_escopo_admin_operacao(o.id));

  IF EXISTS (
    SELECT 1
    FROM jsonb_to_recordset(coalesce(p_permissions, '[]'::jsonb)) x(operacao_id bigint)
    WHERE x.operacao_id IS NULL AND NOT is_super
  ) THEN
    RAISE EXCEPTION 'Permissão consolidada exige Super Administrador';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM jsonb_to_recordset(coalesce(p_permissions, '[]'::jsonb)) x(operacao_id bigint)
    WHERE x.operacao_id IS NOT NULL
      AND NOT (x.operacao_id = ANY(allowed_scope))
  ) THEN
    RAISE EXCEPTION 'Operação fora do escopo do administrador';
  END IF;

  IF is_super THEN
    DELETE FROM public.sustentacao_assistente_permissoes WHERE user_id = p_user_id;
  ELSE
    DELETE FROM public.sustentacao_assistente_permissoes
    WHERE user_id = p_user_id AND operacao_id = ANY(allowed_scope);
  END IF;

  INSERT INTO public.sustentacao_assistente_permissoes (
    user_id, operacao_id, pode_acessar, pode_consultar_indicadores,
    pode_consultar_absenteismo, pode_consultar_plano_acao,
    pode_consultar_sla_neolog, pode_consultar_visao_executiva,
    pode_analisar_consolidado, updated_at
  )
  SELECT
    p_user_id, x.operacao_id, coalesce(x.pode_acessar, false),
    coalesce(x.pode_consultar_indicadores, false),
    coalesce(x.pode_consultar_absenteismo, false),
    coalesce(x.pode_consultar_plano_acao, false),
    coalesce(x.pode_consultar_sla_neolog, false),
    coalesce(x.pode_consultar_visao_executiva, false),
    coalesce(x.pode_analisar_consolidado, false), now()
  FROM jsonb_to_recordset(coalesce(p_permissions, '[]'::jsonb)) x(
    operacao_id bigint,
    pode_acessar boolean,
    pode_consultar_indicadores boolean,
    pode_consultar_absenteismo boolean,
    pode_consultar_plano_acao boolean,
    pode_consultar_sla_neolog boolean,
    pode_consultar_visao_executiva boolean,
    pode_analisar_consolidado boolean
  );

  RETURN jsonb_build_object('ok', true, 'user_id', p_user_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.assistente_registrar_pergunta(
  p_operacao_id bigint,
  p_modulo text,
  p_ano integer,
  p_mes integer,
  p_pergunta text,
  p_modo text DEFAULT 'ask'
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE new_id bigint;
BEGIN
  IF auth.uid() IS NULL OR NOT public.assistente_tem_permissao(p_operacao_id, 'acessar') THEN
    RAISE EXCEPTION 'Usuário sem acesso ao Assistente de Gestão';
  END IF;
  IF length(trim(coalesce(p_pergunta, ''))) = 0 OR length(p_pergunta) > 2000 THEN
    RAISE EXCEPTION 'Pergunta inválida';
  END IF;
  INSERT INTO public.sustentacao_assistente_historico(user_id, operacao_id, modulo, ano, mes, pergunta, modo)
  VALUES (auth.uid(), p_operacao_id, nullif(trim(p_modulo), ''), p_ano, p_mes, trim(p_pergunta), coalesce(nullif(p_modo, ''), 'ask'))
  RETURNING id INTO new_id;
  RETURN new_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.assistente_obter_contexto(
  p_operacao_id bigint DEFAULT NULL,
  p_ano integer DEFAULT NULL,
  p_mes integer DEFAULT NULL,
  p_modulo text DEFAULT NULL,
  p_filtros jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ops bigint[];
  v_year integer := coalesce(p_ano, extract(year FROM current_date)::integer);
  v_month integer;
  v_operation jsonb;
  v_indicators jsonb;
  v_results jsonb;
  v_sla jsonb;
  v_abs jsonb;
  v_actions jsonb;
  v_access jsonb;
BEGIN
  IF v_year < 2000 OR v_year > 2100 THEN
    RAISE EXCEPTION 'Ano inválido';
  END IF;

  IF p_operacao_id IS NULL THEN
    IF NOT public.eh_super_admin() THEN
      RAISE EXCEPTION 'Análise consolidada exige Super Administrador';
    END IF;
    SELECT coalesce(array_agg(o.id ORDER BY o.id), '{}')
      INTO v_ops
    FROM public.sustentacao_operacoes o
    WHERE o.ativo = true
      AND public.tem_acesso_operacao(o.id)
      AND public.assistente_tem_permissao(o.id, 'acessar')
      AND public.assistente_tem_permissao(o.id, 'consolidado');
  ELSE
    IF NOT EXISTS (
      SELECT 1 FROM public.sustentacao_operacoes o
      WHERE o.id = p_operacao_id AND o.ativo = true
    ) OR NOT public.tem_acesso_operacao(p_operacao_id)
      OR NOT public.assistente_tem_permissao(p_operacao_id, 'acessar') THEN
      RAISE EXCEPTION 'Operação não autorizada para o Assistente';
    END IF;
    v_ops := ARRAY[p_operacao_id];
  END IF;

  IF cardinality(v_ops) = 0 THEN
    RAISE EXCEPTION 'Nenhuma operação autorizada para o Assistente';
  END IF;

  SELECT coalesce(NULLIF(p_mes, 0), max(r.mes), 1)
    INTO v_month
  FROM public.sustentacao_resultados r
  WHERE r.operacao_id = ANY(v_ops) AND r.ano = v_year;
  v_month := greatest(1, least(12, v_month));

  SELECT coalesce(jsonb_agg(jsonb_build_object('id', o.id, 'codigo', o.codigo, 'nome', o.nome) ORDER BY o.id), '[]'::jsonb)
    INTO v_operation
  FROM public.sustentacao_operacoes o
  WHERE o.id = ANY(v_ops);

  SELECT coalesce(jsonb_agg(jsonb_build_object(
      'id', i.id, 'operacao_id', i.operacao_id, 'nome', i.nome, 'meta', i.meta,
      'peso', i.peso, 'polaridade', i.polaridade, 'formato', i.formato,
      'ordem', i.ordem, 'objetivo', i.objetivo
    ) ORDER BY i.operacao_id, i.ordem, i.id), '[]'::jsonb)
    INTO v_indicators
  FROM public.sustentacao_indicadores i
  WHERE i.operacao_id = ANY(v_ops)
    AND i.ativo = true
    AND public.assistente_tem_permissao(i.operacao_id, 'indicadores')
    AND public.tem_acesso_indicador(i.operacao_id, i.id, 'VIEW');

  SELECT coalesce(jsonb_agg(jsonb_build_object(
      'id', r.id, 'operacao_id', r.operacao_id, 'indicador_id', r.indicador_id,
      'indicador', i.nome, 'ano', r.ano, 'mes', r.mes, 'resultado', r.resultado,
      'volume_produto', r.volume_produto, 'total_processado', r.total_processado,
      'total_fora_meta', r.total_fora_meta, 'observacao', r.observacao
    ) ORDER BY r.operacao_id, r.mes, i.ordem, r.indicador_id), '[]'::jsonb)
    INTO v_results
  FROM public.sustentacao_resultados r
  JOIN public.sustentacao_indicadores i
    ON i.id = r.indicador_id AND i.operacao_id = r.operacao_id
  WHERE r.operacao_id = ANY(v_ops)
    AND r.ano = v_year
    AND r.mes = v_month
    AND i.ativo = true
    AND public.assistente_tem_permissao(r.operacao_id, 'indicadores')
    AND public.tem_acesso_indicador(r.operacao_id, r.indicador_id, 'VIEW');

  SELECT coalesce(jsonb_agg(jsonb_build_object(
      'id', s.id, 'operacao_id', s.operacao_id, 'ano', s.ano, 'mes', s.mes,
      'indicador', s.indicador, 'indicador_id', s.indicador_id,
      'tipo', s.tipo, 'valor', s.valor
    ) ORDER BY s.operacao_id, s.mes, s.indicador), '[]'::jsonb)
    INTO v_sla
  FROM public.sustentacao_sla_neolog_pontuacoes s
  WHERE s.operacao_id = ANY(v_ops)
    AND s.ano = v_year
    AND public.assistente_tem_permissao(s.operacao_id, 'sla_neolog')
    AND public.tem_acesso_indicador(s.operacao_id, s.indicador_id, 'VIEW');

  SELECT jsonb_build_object(
    'permitido', coalesce(bool_or(public.assistente_tem_permissao(o.id, 'absenteismo')), false),
    'mensal', coalesce((SELECT jsonb_agg(x ORDER BY x.ano, x.mes) FROM (
      SELECT jsonb_build_object(
        'operacao_id', r.operacao_id, 'ano', r.ano, 'mes', r.mes,
        'colaboradores', count(DISTINCT r.colaborador),
        'horas_improdutivas', coalesce(sum(r.horas_improdutivas), 0),
        'horas_disponiveis', coalesce(sum(r.horas_disponiveis), 0),
        'dias_afastamento', coalesce(sum(coalesce(r.dias_falta,0)+coalesce(r.dias_atestado,0)), 0),
        'indice_absenteismo', CASE WHEN coalesce(sum(r.horas_disponiveis),0) > 0
          THEN round((sum(coalesce(r.horas_improdutivas,0))/sum(r.horas_disponiveis))*100,2) ELSE 0 END
      ) AS x, r.ano, r.mes
      FROM public.absenteismo_registros r
      WHERE r.operacao_id = ANY(v_ops)
        AND r.ano = v_year
        AND r.mes IN (v_month, greatest(v_month-1,1))
        AND public.assistente_tem_permissao(r.operacao_id, 'absenteismo')
      GROUP BY r.operacao_id, r.ano, r.mes
    ) q), '[]'::jsonb),
    'motivos', coalesce((SELECT jsonb_agg(x ORDER BY (x->>'horas')::numeric DESC) FROM (
      SELECT jsonb_build_object('operacao_id', r.operacao_id, 'motivo', coalesce(nullif(r.motivo,''),'Não informado'), 'horas', coalesce(sum(r.horas_improdutivas),0)) AS x
      FROM public.absenteismo_registros r
      WHERE r.operacao_id = ANY(v_ops) AND r.ano = v_year AND r.mes = v_month
        AND public.assistente_tem_permissao(r.operacao_id, 'absenteismo')
      GROUP BY r.operacao_id, coalesce(nullif(r.motivo,''),'Não informado')
      ORDER BY sum(r.horas_improdutivas) DESC LIMIT 20
    ) q), '[]'::jsonb),
    'areas', coalesce((SELECT jsonb_agg(x ORDER BY (x->>'horas')::numeric DESC) FROM (
      SELECT jsonb_build_object('operacao_id', r.operacao_id, 'area', coalesce(nullif(r.area,''),nullif(r.local,''),'Não informado'), 'centro_custo', r.centro_custo, 'horas', coalesce(sum(r.horas_improdutivas),0)) AS x
      FROM public.absenteismo_registros r
      WHERE r.operacao_id = ANY(v_ops) AND r.ano = v_year AND r.mes = v_month
        AND public.assistente_tem_permissao(r.operacao_id, 'absenteismo')
      GROUP BY r.operacao_id, coalesce(nullif(r.area,''),nullif(r.local,''),'Não informado'), r.centro_custo
      ORDER BY sum(r.horas_improdutivas) DESC LIMIT 20
    ) q), '[]'::jsonb),
    'pessoas', coalesce((SELECT jsonb_agg(x ORDER BY (x->>'horas')::numeric DESC) FROM (
      SELECT jsonb_build_object('operacao_id', r.operacao_id, 'colaborador', r.colaborador, 'area', max(coalesce(r.area,r.local)), 'horas', coalesce(sum(r.horas_improdutivas),0)) AS x
      FROM public.absenteismo_registros r
      WHERE r.operacao_id = ANY(v_ops) AND r.ano = v_year AND r.mes = v_month
        AND public.assistente_tem_permissao(r.operacao_id, 'absenteismo')
      GROUP BY r.operacao_id, r.colaborador
      ORDER BY sum(r.horas_improdutivas) DESC LIMIT 10
    ) q), '[]'::jsonb),
    'recorrentes', coalesce((SELECT jsonb_agg(x ORDER BY (x->>'horas')::numeric DESC) FROM (
      SELECT jsonb_build_object('operacao_id', r.operacao_id, 'colaborador', r.colaborador, 'meses', count(DISTINCT (r.ano,r.mes)), 'horas', coalesce(sum(r.horas_improdutivas),0)) AS x
      FROM public.absenteismo_registros r
      WHERE r.operacao_id = ANY(v_ops)
        AND public.assistente_tem_permissao(r.operacao_id, 'absenteismo')
      GROUP BY r.operacao_id, r.colaborador
      HAVING count(DISTINCT (r.ano,r.mes)) >= 2
      ORDER BY sum(r.horas_improdutivas) DESC LIMIT 20
    ) q), '[]'::jsonb)
  ) INTO v_abs
  FROM public.sustentacao_operacoes o
  WHERE o.id = ANY(v_ops);

  SELECT coalesce(jsonb_agg(jsonb_build_object(
      'id', p.id, 'operacao_id', p.operacao_id, 'indicador_id', p.indicador_id,
      'acao', p.acao, 'responsavel', p.responsavel, 'data_inicio', p.data_inicio,
      'data_fim', p.data_fim, 'status', p.status, 'observacao', p.observacao,
      'concluido', p.concluido, 'ordem', p.ordem
    ) ORDER BY p.data_fim NULLS LAST, p.ordem, p.id), '[]'::jsonb)
    INTO v_actions
  FROM public.sustentacao_plano_acao p
  WHERE p.operacao_id = ANY(v_ops)
    AND coalesce(p.concluido, false) = false
    AND public.assistente_tem_permissao(p.operacao_id, 'plano_acao')
    AND public.tem_acesso_plano_acao(p.operacao_id, p.indicador_id, 'VIEW');

  v_access := jsonb_build_object(
    'indicadores', EXISTS (SELECT 1 FROM unnest(v_ops) op WHERE public.assistente_tem_permissao(op, 'indicadores')),
    'absenteismo', EXISTS (SELECT 1 FROM unnest(v_ops) op WHERE public.assistente_tem_permissao(op, 'absenteismo')),
    'plano_acao', EXISTS (SELECT 1 FROM unnest(v_ops) op WHERE public.assistente_tem_permissao(op, 'plano_acao')),
    'sla_neolog', EXISTS (SELECT 1 FROM unnest(v_ops) op WHERE public.assistente_tem_permissao(op, 'sla_neolog')),
    'visao_executiva', EXISTS (SELECT 1 FROM unnest(v_ops) op WHERE public.assistente_tem_permissao(op, 'visao_executiva')),
    'consolidado', p_operacao_id IS NULL
  );

  RETURN jsonb_build_object(
    'permitido', true,
    'operacoes', v_operation,
    'ano', v_year,
    'mes', v_month,
    'modulo', p_modulo,
    'filtros', coalesce(p_filtros, '{}'::jsonb),
    'atualizado_em', now(),
    'indicadores', CASE WHEN (v_access->>'indicadores')::boolean THEN v_indicators ELSE '[]'::jsonb END,
    'resultados', CASE WHEN (v_access->>'indicadores')::boolean THEN v_results ELSE '[]'::jsonb END,
    'sla', CASE WHEN (v_access->>'sla_neolog')::boolean THEN v_sla ELSE '[]'::jsonb END,
    'absenteismo', CASE WHEN (v_access->>'absenteismo')::boolean THEN v_abs ELSE jsonb_build_object('permitido', false, 'mensal','[]'::jsonb, 'motivos','[]'::jsonb, 'areas','[]'::jsonb, 'pessoas','[]'::jsonb, 'recorrentes','[]'::jsonb) END,
    'acoes', CASE WHEN (v_access->>'plano_acao')::boolean THEN v_actions ELSE '[]'::jsonb END,
    'acessos', v_access
  );
END;
$$;

-- Administradores atuais recebem o Assistente habilitado para suas operações, sem tocar nos dados de negócio.
INSERT INTO public.sustentacao_assistente_permissoes (
  user_id, operacao_id, pode_acessar, pode_consultar_indicadores,
  pode_consultar_absenteismo, pode_consultar_plano_acao,
  pode_consultar_sla_neolog, pode_consultar_visao_executiva,
  pode_analisar_consolidado, updated_at
)
SELECT su.user_id, uo.operacao_id, true, true, true, true, true, true,
       su.perfil IN ('super_admin','admin'), now()
FROM public.sustentacao_usuarios su
JOIN public.sustentacao_usuario_operacoes uo ON uo.user_id = su.user_id AND uo.ativo = true
JOIN public.sustentacao_operacoes o ON o.id = uo.operacao_id AND o.ativo = true
WHERE su.ativo = true
  AND su.perfil IN ('super_admin','admin','administrador_operacao','gestor')
ON CONFLICT (user_id, (coalesce(operacao_id, 0))) DO UPDATE SET
  pode_acessar = true,
  pode_consultar_indicadores = true,
  pode_consultar_absenteismo = true,
  pode_consultar_plano_acao = true,
  pode_consultar_sla_neolog = true,
  pode_consultar_visao_executiva = true,
  pode_analisar_consolidado = excluded.pode_analisar_consolidado,
  updated_at = now();

INSERT INTO public.sustentacao_assistente_permissoes (
  user_id, operacao_id, pode_acessar, pode_consultar_indicadores,
  pode_consultar_absenteismo, pode_consultar_plano_acao,
  pode_consultar_sla_neolog, pode_consultar_visao_executiva,
  pode_analisar_consolidado, updated_at
)
SELECT su.user_id, NULL, true, true, true, true, true, true, true, now()
FROM public.sustentacao_usuarios su
WHERE su.ativo = true AND su.perfil IN ('super_admin','admin')
ON CONFLICT (user_id, (coalesce(operacao_id, 0))) DO UPDATE SET
  pode_acessar = true,
  pode_consultar_indicadores = true,
  pode_consultar_absenteismo = true,
  pode_consultar_plano_acao = true,
  pode_consultar_sla_neolog = true,
  pode_consultar_visao_executiva = true,
  pode_analisar_consolidado = true,
  updated_at = now();

REVOKE ALL ON FUNCTION public.assistente_tem_permissao(bigint,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_save_assistant_access(uuid,jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.assistente_registrar_pergunta(bigint,text,integer,integer,text,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.assistente_obter_contexto(bigint,integer,integer,text,jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.assistente_tem_permissao(bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_save_assistant_access(uuid,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assistente_registrar_pergunta(bigint,text,integer,integer,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assistente_obter_contexto(bigint,integer,integer,text,jsonb) TO authenticated;

COMMENT ON TABLE public.sustentacao_assistente_permissoes IS 'Permissões do Assistente de Gestão por usuário e operação; NULL representa escopo consolidado do Super Administrador.';
COMMENT ON TABLE public.sustentacao_assistente_historico IS 'Histórico de perguntas do Assistente; não armazena tokens, senhas ou chaves de API.';
COMMENT ON FUNCTION public.assistente_obter_contexto(bigint,integer,integer,text,jsonb) IS 'Contexto somente leitura, filtrado por Auth, operação, permissões do Assistente e RLS lógico das tabelas de negócio.';
