-- Notificações, lembretes e portal externo seguro para Planos de Ação.
-- Migration aditiva: não remove nem recria dados operacionais existentes.
-- O envio de e-mail é executado por Edge Function via Resend; a ausência da chave
-- nunca deve impedir a gravação de uma ação.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

ALTER TABLE public.sustentacao_plano_acao
  ADD COLUMN IF NOT EXISTS responsavel_tipo text NOT NULL DEFAULT 'NENHUM',
  ADD COLUMN IF NOT EXISTS responsavel_email text,
  ADD COLUMN IF NOT EXISTS prioridade text,
  ADD COLUMN IF NOT EXISTS external_access_expires_at timestamptz,
  ADD COLUMN IF NOT EXISTS ultimo_lembrete_em timestamptz,
  ADD COLUMN IF NOT EXISTS proximo_lembrete_em timestamptz,
  ADD COLUMN IF NOT EXISTS criado_por_user_id uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS criado_em timestamptz,
  ADD COLUMN IF NOT EXISTS atualizado_por_user_id uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS concluido_por_user_id uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS concluido_em timestamptz;

UPDATE public.sustentacao_plano_acao
SET responsavel_tipo = CASE
  WHEN responsavel_user_id IS NOT NULL THEN 'PLATAFORMA'
  WHEN nullif(btrim(coalesce(responsavel_email, '')), '') IS NOT NULL THEN 'EXTERNO'
  ELSE 'NENHUM'
END
WHERE responsavel_tipo IS NULL OR responsavel_tipo = '';

ALTER TABLE public.sustentacao_plano_acao
  DROP CONSTRAINT IF EXISTS sustentacao_plano_acao_responsavel_tipo_check;
ALTER TABLE public.sustentacao_plano_acao
  ADD CONSTRAINT sustentacao_plano_acao_responsavel_tipo_check
  CHECK (responsavel_tipo IN ('PLATAFORMA', 'EXTERNO', 'NENHUM'));

CREATE INDEX IF NOT EXISTS sustentacao_plano_acao_responsavel_email_idx
  ON public.sustentacao_plano_acao (responsavel_email, operacao_id);
CREATE INDEX IF NOT EXISTS sustentacao_plano_acao_reminder_idx
  ON public.sustentacao_plano_acao (proximo_lembrete_em, concluido);

COMMENT ON COLUMN public.sustentacao_plano_acao.responsavel_tipo IS
  'Tipo do responsável: PLATAFORMA, EXTERNO ou NENHUM.';
COMMENT ON COLUMN public.sustentacao_plano_acao.responsavel_email IS
  'E-mail do responsável externo ou cópia do usuário da plataforma para notificações.';
COMMENT ON COLUMN public.sustentacao_plano_acao.external_access_expires_at IS
  'Data de expiração do acesso somente leitura do portal após a conclusão.';

CREATE TABLE IF NOT EXISTS public.sustentacao_acao_portal_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  action_id bigint NOT NULL REFERENCES public.sustentacao_plano_acao(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  token_ciphertext text NOT NULL,
  issued_by_user_id uuid REFERENCES auth.users(id),
  issued_at timestamptz NOT NULL DEFAULT now(),
  last_accessed_at timestamptz,
  revoked_at timestamptz,
  expires_at timestamptz,
  completed_read_until timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sustentacao_acao_portal_tokens_action_idx
  ON public.sustentacao_acao_portal_tokens(action_id, revoked_at, expires_at);

CREATE TABLE IF NOT EXISTS public.sustentacao_acao_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_id bigint NOT NULL REFERENCES public.sustentacao_plano_acao(id) ON DELETE CASCADE,
  operacao_id bigint NOT NULL REFERENCES public.sustentacao_operacoes(id),
  tipo text NOT NULL,
  actor_user_id uuid REFERENCES auth.users(id),
  actor_type text NOT NULL DEFAULT 'PLATAFORMA',
  actor_email text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sustentacao_acao_eventos_action_idx
  ON public.sustentacao_acao_eventos(action_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.sustentacao_acao_notificacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_id bigint NOT NULL REFERENCES public.sustentacao_plano_acao(id) ON DELETE CASCADE,
  operacao_id bigint NOT NULL REFERENCES public.sustentacao_operacoes(id),
  tipo text NOT NULL CHECK (tipo IN ('ATRIBUICAO', 'LEMBRETE', 'REENVIO')),
  destinatario_tipo text NOT NULL CHECK (destinatario_tipo IN ('PLATAFORMA', 'EXTERNO')),
  destinatario_user_id uuid REFERENCES auth.users(id),
  destinatario_email text NOT NULL,
  status text NOT NULL DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE', 'PROCESSANDO', 'ENVIADO', 'FALHA', 'CANCELADO')),
  dedupe_key text NOT NULL UNIQUE,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  provider_message_id text,
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 8,
  scheduled_at timestamptz NOT NULL DEFAULT now(),
  processing_started_at timestamptz,
  sent_at timestamptz,
  last_error text,
  next_attempt_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sustentacao_acao_notificacoes_due_idx
  ON public.sustentacao_acao_notificacoes(status, scheduled_at, next_attempt_at);
CREATE INDEX IF NOT EXISTS sustentacao_acao_notificacoes_action_idx
  ON public.sustentacao_acao_notificacoes(action_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.sustentacao_acao_lembrete_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operacao_id bigint NOT NULL UNIQUE REFERENCES public.sustentacao_operacoes(id) ON DELETE CASCADE,
  estrategia text NOT NULL DEFAULT 'SEMANAL' CHECK (estrategia IN ('SEMANAL', 'TRES_DIAS_ANTES', 'NO_VENCIMENTO', 'APOS_VENCIMENTO')),
  horario_local time NOT NULL DEFAULT '09:00',
  timezone text NOT NULL DEFAULT 'America/Sao_Paulo',
  intervalo_dias integer NOT NULL DEFAULT 7 CHECK (intervalo_dias >= 1 AND intervalo_dias <= 90),
  ativo boolean NOT NULL DEFAULT true,
  criado_at timestamptz NOT NULL DEFAULT now(),
  atualizado_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.sustentacao_acao_lembrete_config (operacao_id, estrategia, horario_local, timezone, intervalo_dias)
SELECT id, 'SEMANAL', '09:00', 'America/Sao_Paulo', 7
FROM public.sustentacao_operacoes
WHERE ativo = true
ON CONFLICT (operacao_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.sustentacao_acao_worker_secrets (
  id integer PRIMARY KEY CHECK (id = 1),
  worker_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.sustentacao_acao_worker_secrets (id, worker_key)
VALUES (1, encode(gen_random_bytes(32), 'hex'))
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.action_next_weekly_reminder(p_base timestamptz DEFAULT now())
RETURNS timestamptz
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT ((date_trunc('day', p_base AT TIME ZONE 'America/Sao_Paulo') + interval '7 days' + interval '9 hours') AT TIME ZONE 'America/Sao_Paulo');
$$;

CREATE OR REPLACE FUNCTION public.normalize_sustentacao_plano_acao_notification_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  email_value text;
BEGIN
  IF NEW.responsavel_user_id IS NOT NULL THEN
    SELECT lower(email) INTO email_value
    FROM public.sustentacao_usuarios
    WHERE user_id = NEW.responsavel_user_id
    LIMIT 1;
    NEW.responsavel_tipo := 'PLATAFORMA';
    NEW.responsavel_email := coalesce(email_value, nullif(lower(btrim(NEW.responsavel_email)), ''));
  ELSIF upper(coalesce(NEW.responsavel_tipo, '')) = 'EXTERNO'
        AND nullif(btrim(coalesce(NEW.responsavel_email, '')), '') IS NOT NULL THEN
    NEW.responsavel_tipo := 'EXTERNO';
    NEW.responsavel_email := lower(btrim(NEW.responsavel_email));
  ELSE
    NEW.responsavel_tipo := 'NENHUM';
    NEW.responsavel_email := nullif(lower(btrim(coalesce(NEW.responsavel_email, ''))), '');
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.concluido = true AND coalesce(OLD.concluido, false) = false THEN
    NEW.external_access_expires_at := now() + interval '30 days';
  ELSIF TG_OP = 'UPDATE' AND NEW.concluido = false AND OLD.concluido = true THEN
    NEW.external_access_expires_at := null;
  END IF;

  IF NEW.proximo_lembrete_em IS NULL
     AND NEW.concluido = false
     AND NEW.responsavel_email IS NOT NULL THEN
    NEW.proximo_lembrete_em := public.action_next_weekly_reminder(now());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sustentacao_plano_acao_notification_fields ON public.sustentacao_plano_acao;
CREATE TRIGGER sustentacao_plano_acao_notification_fields
BEFORE INSERT OR UPDATE ON public.sustentacao_plano_acao
FOR EACH ROW EXECUTE FUNCTION public.normalize_sustentacao_plano_acao_notification_fields();

CREATE OR REPLACE FUNCTION public.populate_sustentacao_plano_acao_audit_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := auth.uid();
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.criado_por_user_id := coalesce(NEW.criado_por_user_id, actor);
    NEW.criado_em := coalesce(NEW.criado_em, now());
    NEW.atualizado_por_user_id := coalesce(NEW.atualizado_por_user_id, actor);
    IF NEW.concluido = true THEN
      NEW.concluido_por_user_id := coalesce(NEW.concluido_por_user_id, actor);
      NEW.concluido_em := coalesce(NEW.concluido_em, now());
    END IF;
  ELSE
    NEW.atualizado_por_user_id := coalesce(actor, NEW.atualizado_por_user_id);
    IF NEW.concluido = true AND coalesce(OLD.concluido, false) = false THEN
      NEW.concluido_por_user_id := coalesce(actor, NEW.concluido_por_user_id);
      NEW.concluido_em := coalesce(NEW.concluido_em, now());
    ELSIF NEW.concluido = false AND coalesce(OLD.concluido, false) = true THEN
      NEW.concluido_por_user_id := null;
      NEW.concluido_em := null;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sustentacao_plano_acao_audit_fields ON public.sustentacao_plano_acao;
CREATE TRIGGER sustentacao_plano_acao_audit_fields
BEFORE INSERT OR UPDATE ON public.sustentacao_plano_acao
FOR EACH ROW EXECUTE FUNCTION public.populate_sustentacao_plano_acao_audit_fields();

CREATE OR REPLACE FUNCTION public.record_sustentacao_plano_acao_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := auth.uid();
  recipient text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.sustentacao_acao_eventos(action_id, operacao_id, tipo, actor_user_id, actor_type, metadata)
    VALUES (NEW.id, NEW.operacao_id, 'ACAO_CRIADA', actor, 'PLATAFORMA', jsonb_build_object('responsavel_tipo', NEW.responsavel_tipo));
    IF NEW.responsavel_email IS NOT NULL THEN
      INSERT INTO public.sustentacao_acao_eventos(action_id, operacao_id, tipo, actor_user_id, actor_type, metadata)
      VALUES (NEW.id, NEW.operacao_id, 'RESPONSAVEL_ATRIBUIDO', actor, CASE WHEN NEW.responsavel_tipo = 'EXTERNO' THEN 'EXTERNO' ELSE 'PLATAFORMA' END, jsonb_build_object('email', NEW.responsavel_email));
      INSERT INTO public.sustentacao_acao_notificacoes(action_id, operacao_id, tipo, destinatario_tipo, destinatario_user_id, destinatario_email, dedupe_key, payload)
      VALUES (NEW.id, NEW.operacao_id, 'ATRIBUICAO', NEW.responsavel_tipo, NEW.responsavel_user_id, NEW.responsavel_email, 'assignment:' || NEW.id::text || ':' || NEW.responsavel_email, jsonb_build_object('action_id', NEW.id))
      ON CONFLICT (dedupe_key) DO NOTHING;
    END IF;
    RETURN NEW;
  END IF;

  IF NEW.responsavel_user_id IS DISTINCT FROM OLD.responsavel_user_id
     OR (NEW.responsavel_user_id IS NULL AND NEW.responsavel_email IS DISTINCT FROM OLD.responsavel_email) THEN
    recipient := coalesce(NEW.responsavel_email, '');
    IF recipient <> '' AND NEW.concluido = false THEN
      INSERT INTO public.sustentacao_acao_eventos(action_id, operacao_id, tipo, actor_user_id, actor_type, metadata)
      VALUES (NEW.id, NEW.operacao_id, 'RESPONSAVEL_ATRIBUIDO', actor, CASE WHEN NEW.responsavel_tipo = 'EXTERNO' THEN 'EXTERNO' ELSE 'PLATAFORMA' END, jsonb_build_object('email', recipient));
      INSERT INTO public.sustentacao_acao_notificacoes(action_id, operacao_id, tipo, destinatario_tipo, destinatario_user_id, destinatario_email, dedupe_key, payload)
      VALUES (NEW.id, NEW.operacao_id, 'ATRIBUICAO', NEW.responsavel_tipo, NEW.responsavel_user_id, recipient, 'assignment:' || NEW.id::text || ':' || recipient, jsonb_build_object('action_id', NEW.id))
      ON CONFLICT (dedupe_key) DO NOTHING;
    END IF;
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status OR NEW.concluido IS DISTINCT FROM OLD.concluido THEN
    INSERT INTO public.sustentacao_acao_eventos(action_id, operacao_id, tipo, actor_user_id, actor_type, metadata)
    VALUES (NEW.id, NEW.operacao_id, CASE WHEN NEW.concluido THEN 'ACAO_CONCLUIDA' ELSE 'STATUS_ALTERADO' END, actor, 'PLATAFORMA', jsonb_build_object('status', NEW.status, 'concluido', NEW.concluido));
    IF NEW.concluido THEN
      UPDATE public.sustentacao_acao_notificacoes
      SET status = 'CANCELADO', updated_at = now(), last_error = 'Ação concluída antes do envio.'
      WHERE action_id = NEW.id AND status IN ('PENDENTE', 'PROCESSANDO') AND tipo = 'LEMBRETE';
      UPDATE public.sustentacao_acao_portal_tokens
      SET expires_at = now() + interval '30 days', completed_read_until = now() + interval '30 days', updated_at = now()
      WHERE action_id = NEW.id AND revoked_at IS NULL;
    END IF;
  END IF;

  IF NEW.andamento IS DISTINCT FROM OLD.andamento OR NEW.observacao IS DISTINCT FROM OLD.observacao THEN
    INSERT INTO public.sustentacao_acao_eventos(action_id, operacao_id, tipo, actor_user_id, actor_type, metadata)
    VALUES (NEW.id, NEW.operacao_id, 'RESPOSTA_REGISTRADA', actor, 'PLATAFORMA', jsonb_build_object('tem_andamento', NEW.andamento IS NOT NULL, 'tem_observacao', NEW.observacao IS NOT NULL));
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sustentacao_plano_acao_event_audit ON public.sustentacao_plano_acao;
CREATE TRIGGER sustentacao_plano_acao_event_audit
AFTER INSERT OR UPDATE ON public.sustentacao_plano_acao
FOR EACH ROW EXECUTE FUNCTION public.record_sustentacao_plano_acao_event();

CREATE OR REPLACE FUNCTION public.claim_sustentacao_acao_notificacoes(p_limit integer DEFAULT 25)
RETURNS SETOF public.sustentacao_acao_notificacoes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  UPDATE public.sustentacao_acao_notificacoes n
  SET status = 'PROCESSANDO', attempts = n.attempts + 1, processing_started_at = now(), updated_at = now()
  WHERE n.id IN (
    SELECT q.id
    FROM public.sustentacao_acao_notificacoes q
    WHERE q.status IN ('PENDENTE', 'FALHA')
      AND q.attempts < q.max_attempts
      AND q.scheduled_at <= now()
      AND (q.next_attempt_at IS NULL OR q.next_attempt_at <= now())
    ORDER BY q.scheduled_at, q.id
    FOR UPDATE SKIP LOCKED
    LIMIT greatest(1, least(p_limit, 100))
  )
  RETURNING n.*;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_sustentacao_acao_notification(
  p_id bigint,
  p_status text,
  p_error text DEFAULT NULL,
  p_provider_message_id text DEFAULT NULL,
  p_next_attempt_at timestamptz DEFAULT NULL
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.sustentacao_acao_notificacoes
  SET status = p_status,
      last_error = p_error,
      provider_message_id = coalesce(p_provider_message_id, provider_message_id),
      sent_at = CASE WHEN p_status = 'ENVIADO' THEN now() ELSE sent_at END,
      next_attempt_at = p_next_attempt_at,
      updated_at = now()
  WHERE id = p_id;
$$;

ALTER TABLE public.sustentacao_acao_portal_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustentacao_acao_notificacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustentacao_acao_worker_secrets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustentacao_acao_lembrete_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sustentacao_acao_eventos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sustentacao_acao_eventos_select ON public.sustentacao_acao_eventos;
CREATE POLICY sustentacao_acao_eventos_select
ON public.sustentacao_acao_eventos
FOR SELECT TO authenticated
USING (
  public.eh_super_admin()
  OR EXISTS (
    SELECT 1
    FROM public.sustentacao_plano_acao a
    WHERE a.id = sustentacao_acao_eventos.action_id
      AND public.tem_acesso_plano_acao_linha(a.operacao_id, a.indicador_id, 'VIEW', a.responsavel_user_id)
  )
);

REVOKE ALL ON public.sustentacao_acao_portal_tokens FROM anon, authenticated;
REVOKE ALL ON public.sustentacao_acao_notificacoes FROM anon, authenticated;
REVOKE ALL ON public.sustentacao_acao_worker_secrets FROM anon, authenticated;
REVOKE ALL ON public.sustentacao_acao_lembrete_config FROM anon, authenticated;
GRANT SELECT ON public.sustentacao_acao_eventos TO authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_sustentacao_acao_notificacoes(integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_sustentacao_acao_notification(bigint,text,text,text,timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_sustentacao_acao_notificacoes(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_sustentacao_acao_notification(bigint,text,text,text,timestamptz) TO service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('plano-acao-evidencias', 'plano-acao-evidencias', false, 10485760, ARRAY['image/*', 'application/pdf']::text[])
ON CONFLICT (id) DO UPDATE
SET public = false, file_size_limit = 10485760, allowed_mime_types = ARRAY['image/*', 'application/pdf']::text[];

DROP POLICY IF EXISTS plano_acao_evidencias_select ON storage.objects;
CREATE POLICY plano_acao_evidencias_select
ON storage.objects
FOR SELECT TO authenticated
USING (
  bucket_id = 'plano-acao-evidencias'
  AND split_part(name, '/', 1) ~ '^[0-9]+$'
  AND EXISTS (
    SELECT 1
    FROM public.sustentacao_plano_acao a
    WHERE a.id = split_part(name, '/', 1)::bigint
      AND public.tem_acesso_plano_acao_linha(a.id, a.indicador_id, 'VIEW', a.responsavel_user_id)
  )
);

DO $$
DECLARE
  job_id bigint;
BEGIN
  FOR job_id IN SELECT jobid FROM cron.job WHERE jobname = 'sustentacao-acao-notificacoes' LOOP
    PERFORM cron.unschedule(job_id);
  END LOOP;
  PERFORM cron.schedule(
    'sustentacao-acao-notificacoes',
    '*/5 * * * *',
    $cron$
      SELECT net.http_post(
        url := 'https://nemvssopcgmfxjndpmlw.supabase.co/functions/v1/action-notifications',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-action-worker-key', (SELECT worker_key FROM public.sustentacao_acao_worker_secrets WHERE id = 1)
        ),
        body := '{"mode":"process_due"}'::jsonb
      );
    $cron$
  );
END $$;

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON public.sustentacao_acao_eventos TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
