-- Configuração dos cards superiores do Plano de Sustentação por operação.
-- Não altera indicadores, resultados, planos de ação ou Absenteísmo.
CREATE TABLE IF NOT EXISTS public.sustentacao_configuracoes_operacao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operacao_id bigint NOT NULL REFERENCES public.sustentacao_operacoes(id) ON DELETE CASCADE,
  responsavel_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  responsavel_nome text,
  polaridade text NOT NULL DEFAULT '',
  objetivo text NOT NULL DEFAULT '',
  formato_calculo text NOT NULL DEFAULT '',
  peso numeric(8,2),
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS sustentacao_configuracoes_operacao_one_active
  ON public.sustentacao_configuracoes_operacao(operacao_id)
  WHERE ativo = true;

CREATE INDEX IF NOT EXISTS sustentacao_configuracoes_operacao_responsavel_idx
  ON public.sustentacao_configuracoes_operacao(responsavel_user_id);

ALTER TABLE public.sustentacao_configuracoes_operacao ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sustentacao_configuracoes_operacao_select ON public.sustentacao_configuracoes_operacao;
CREATE POLICY sustentacao_configuracoes_operacao_select
  ON public.sustentacao_configuracoes_operacao
  FOR SELECT TO authenticated
  USING (tem_acesso_modulo(operacao_id, 'PLANO_SUSTENTACAO', 'VIEW'));

DROP POLICY IF EXISTS sustentacao_configuracoes_operacao_insert ON public.sustentacao_configuracoes_operacao;
CREATE POLICY sustentacao_configuracoes_operacao_insert
  ON public.sustentacao_configuracoes_operacao
  FOR INSERT TO authenticated
  WITH CHECK (eh_admin_sustentacao());

DROP POLICY IF EXISTS sustentacao_configuracoes_operacao_update ON public.sustentacao_configuracoes_operacao;
CREATE POLICY sustentacao_configuracoes_operacao_update
  ON public.sustentacao_configuracoes_operacao
  FOR UPDATE TO authenticated
  USING (eh_admin_sustentacao())
  WITH CHECK (eh_admin_sustentacao());

DROP POLICY IF EXISTS sustentacao_configuracoes_operacao_delete ON public.sustentacao_configuracoes_operacao;
CREATE POLICY sustentacao_configuracoes_operacao_delete
  ON public.sustentacao_configuracoes_operacao
  FOR DELETE TO authenticated
  USING (eh_admin_sustentacao());

INSERT INTO public.sustentacao_configuracoes_operacao
  (operacao_id, responsavel_user_id, responsavel_nome, polaridade, objetivo, formato_calculo, peso, ativo, updated_by)
SELECT op.id, u.user_id, 'Willian Soares',
       'Atingir as metas propostas em pelo menos 8 itens',
       'Atendimento aos SLA/metas', '#', 10, true, u.user_id
FROM public.sustentacao_operacoes op
JOIN public.sustentacao_usuarios u
  ON lower(u.email) = lower('willian.soares@mundiallogistics.com.br')
WHERE op.codigo = 'MATRIZ'
  AND u.ativo = true
ON CONFLICT (operacao_id) WHERE ativo = true DO UPDATE
SET responsavel_user_id = EXCLUDED.responsavel_user_id,
    responsavel_nome = EXCLUDED.responsavel_nome,
    polaridade = EXCLUDED.polaridade,
    objetivo = EXCLUDED.objetivo,
    formato_calculo = EXCLUDED.formato_calculo,
    peso = EXCLUDED.peso,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by;
